### ISSUE TITLE
[Feature Request] Split transaction 

### ISSUE THREAD

**Issue by maxlandry** [jameskokoska/Cashew#447] opened 2024-09-28 23:06 UTC
**Describe the solution you'd like**
The ability to split a transaction between two or multiple categories based. We could choose an amount or a percentage for each category. For example, a $200 trip to Walmart could be split $76 for video games and $124 for groceries.

**Describe alternatives you've considered**
I tried to add multiple transactions for the same purchase, for example, but I was very complicated.

**Comment by jameskokoska** [comment] 2024-09-28 23:09
This is a direct duplicate of https://github.com/jameskokoska/Cashew/issues/65

**Closed by jameskokoska** 2024-09-28 23:09 UTC
Labels: enhancement
