### ISSUE TITLE
[Feature Request] Tags

### ISSUE THREAD

**Issue by bitSheriff** [jameskokoska/Cashew#487] opened 2024-10-27 13:01 UTC
# Feature Request: Tagging System for Transactions

## Summary

This pull request proposes adding a tagging system to enhance the transaction categorization in Cashew. Currently, users categorize their spending by specific categories (e.g., Food, Freetime), but there are instances where further flexibility is needed. For example, transactions with the same store name might belong to different categories depending on the context. By introducing tags, users could group and filter transactions by tags in addition to categories, allowing for more dynamic and customizable tracking.

## Use Case

A tagging feature would enable users to add additional context to their transactions. Here’s a scenario:

- **Example:** A user frequently shops at a store called "GreenMart." Sometimes, they buy groceries (Food category), and other times, they purchase leisure items (Freetime category). By tagging each transaction with "GreenMart," the user could track all expenses related to this store, regardless of the category assigned.

## Proposed Solution

1. **Tag Creation**: Allow users to create custom tags for transactions.
2. **Tag Assignment**: Enable tags to be assigned to transactions, regardless of the category.
3. **Filtering by Tags**: Add a filter option so users can view transactions based on tags (e.g., all transactions tagged "GreenMart").
4. **Tag Management**: Implement a simple UI for users to view, rename, or delete tags.

## Potential Benefits

- **Enhanced Flexibility**: Allows users to organize and track spending patterns more granularly.
- **Improved Reporting**: Users can generate specific reports or summaries based on tags, providing more insights into spending habits.
- **Increased Usability**: A tagging system provides a common, intuitive way to manage diverse transaction types without modifying the core categorization structure.

## Conclusion

Adding a tagging system to Cashew would provide users with a powerful tool to manage and categorize their spending more effectively. This feature would make Cashew a more flexible and user-friendly expense tracking solution.

Thank you for considering this feature!

**Comment by jameskokoska** [comment] 2024-10-27 14:18
This is a direct duplicate of https://github.com/jameskokoska/Cashew/issues/107. Please do not duplicate issues.

**Closed by jameskokoska** 2024-10-27 14:18 UTC
Labels: enhancement
