### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by kevinah95** [jameskokoska/Cashew#533] opened 2024-11-29 22:04 UTC
**Is your feature request related to a problem? Please describe.**

Currently, CashewApp does not support entering a transaction with multiple currencies in a single operation. This becomes an issue when managing accounts or expenses in different currencies and needing to see the conversions directly while registering the transaction.

**Describe the solution you'd like**

Add a currency selection button to the transaction input keyboard, as shown in the attached images from the 1Money app by Pixel.
- This button, located in the bottom left corner of the keyboard, would open a screen to select the desired currency for the transaction.
- Once selected, both currencies would appear on the transaction screen: the primary currency (e.g., Costa Rican colón) and the selected currency (e.g., US dollar), along with their automatic conversion.
- Additionally, it would allow users to independently edit the amounts for both currencies using the same keyboard, and the system would automatically adjust the conversion based on the configured exchange rate.

**Describe alternatives you've considered**

- Currently, I use other apps like 1Money, which have this functionality built-in. However, it would be ideal to have this support directly in CashewApp to centralize my financial management.
- Alternatively, I could manually calculate conversions and register two separate transactions, but this is cumbersome and inefficient.

**Additional context**

I have included screenshots of how this feature works in the 1Money app for visual reference. This feature greatly simplifies managing multiple currencies and makes recording international transactions more efficient.

Attachments:

- Button on the bottom left corner (₡):
<img src="https://github.com/user-attachments/assets/96cd165b-1187-49b3-a3ab-bf8d377904ad" data-canonical-src="https://github.com/user-attachments/assets/96cd165b-1187-49b3-a3ab-bf8d377904ad" width="200"  />

- Currency selector:
<img src="https://github.com/user-attachments/assets/46f66593-cc92-431d-9d99-3a7b89e2f80e" data-canonical-src="https://github.com/user-attachments/assets/46f66593-cc92-431d-9d99-3a7b89e2f80e" width="200"  />

- Transaction window showing the two currencies, its convertion and giving the chance to modify the amount per currency:
<img src="https://github.com/user-attachments/assets/a72becc6-3363-494a-870f-5295cf821a8a" data-canonical-src="https://github.com/user-attachments/assets/a72becc6-3363-494a-870f-5295cf821a8a" width="200" />

**Comment by jameskokoska** [comment] 2024-11-29 22:06
Duplicate of https://github.com/jameskokoska/Cashew/issues/109

**Closed by jameskokoska** 2024-11-29 22:06 UTC
Labels: enhancement

**Comment by kevinah95** [comment] 2024-12-03 02:37
@jameskokoska Do you have plans to add this feature to your roadmap?, I think this is very helpful. I mean, today I am doing my personal budget, and I am from Costa Rica, and the bank accepts colon (costarrican currency) and dollar. Some recurrent transactions are done in dollars because they are international services.
