### ISSUE TITLE
[Feature Request] A Credit Card Option

### ISSUE THREAD

**Issue by Nightangel224** [jameskokoska/Cashew#161] opened 2024-02-27 00:12 UTC
Right now there it is challenging to have credit cards tracked on the app. I am currently having to keep them as loans, but every time I have to add interest or anything it needs to be collected into an account. 

I would love to see a credit option. Maybe input the interest rate and the day it charges interest so it automatically does it. 

I feel like this is about the only thing that is missing from the app. I truly think this is a nearly perfect budgeting app, it just needs a credit section for the society we live in today.

**Comment by jameskokoska** [comment] 2024-02-27 00:14
Duplicate of https://github.com/jameskokoska/Cashew/issues/124

**Closed by jameskokoska** 2024-02-27 00:14 UTC
Labels: enhancement
