### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Umang-Vadadoriya** [jameskokoska/Cashew#410] opened 2024-09-08 10:49 UTC
Hey @jameskokoska ,
Why Suddenly stopped release here on GitHub?

NOTE TO THE SUBMITTER
Loving your work, Keep Going. 👏🏻

**Comment by jameskokoska** [comment] 2024-09-08 13:35
Duplicate of https://github.com/jameskokoska/Cashew/issues/396

Glad you enjoy Cashew :‎)

**Closed by jameskokoska** 2024-09-08 13:35 UTC
Labels: question
