### ISSUE TITLE
Budgeting with different Currencies not converting correctly

### ISSUE THREAD

**Issue by OmkoBass** [jameskokoska/Cashew#41] opened 2023-11-21 21:59 UTC
Budgeting currencies are not correct.

Steps to reproduce
- Create an account in Currency X
- Create an account in Currency Y
- Create a budget in Currency X
- Have both of those visible with the `Accounts` widget on the home page
- Click on the Currency Y
- You will see the budget convert to the currency Y without being converted to the appropriate amount.

**Comment by jameskokoska** [comment] 2023-11-21 22:12
Duplicate of https://github.com/jameskokoska/Cashew/issues/29 but for budgets. Has been fixed, awaiting approval from all platforms for release because of new database migration code.

**Closed** 2023-11-21 22:12 UTC
