### ISSUE TITLE
[Feature Request] Not able to login without adding google account

### ISSUE THREAD

**Issue by contact-maximux** [jameskokoska/Cashew#374] opened 2024-08-14 09:22 UTC
**Describe the bug**
I must able to log with just email/password
**How to reproduce**
Try to login with new email/password. It ask to add account in mobile
**Screenshots/videos**
It does not seem fait to use only mobile account for cashew login
please add email/password login also. and use share drive folder for sync

**Comment by jameskokoska** [comment] 2024-08-14 13:06
Duplicate of https://github.com/jameskokoska/Cashew/issues/84

**Closed** 2024-08-14 13:07 UTC
Labels: enhancement
