### ISSUE TITLE
[Feature Request] Add support for stocks

### ISSUE THREAD

**Issue by amartin68000** [jameskokoska/Cashew#567] opened 2024-12-30 10:49 UTC
**Is your feature request related to a problem? Please describe.**
Having multiple brokers and banks accounts can be a nightmare, so adding support for stocks in Cashew would ease the life of many of us investors. 

**Describe the solution you'd like**
I'd start with something very simple, like retrieving companies and stock values from most common markets using public and free APIs. 

**Describe alternatives you've considered**
I've tried other tools like https://www.portfolio-performance.info/, but it's not easy to use and Android app is quite limited. Only a very few of features would be required to track stocks for most of the public. 

**Additional context**
No additional comments. 

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-12-30 16:31
Direct duplicate of https://github.com/jameskokoska/Cashew/issues/140

**Closed by jameskokoska** 2024-12-30 16:31 UTC
Labels: enhancement
