### ISSUE TITLE
[Feature Request] Google Sheets Import Templete with Sub-category column

### ISSUE THREAD

**Issue by Parminder641** [jameskokoska/Cashew#147] opened 2024-02-08 20:28 UTC
In Google Sheets  Import Templete, please add the Sub-category column in Sample Template of Google Sheets. I want to import my old transactions data of 4 years from another app (ClevMoney) & adding sub-category to each transaction will be too much work.

**Describe the solution you'd like**
If I have sub-category column then all the transaction will be sorted automatically.

**Describe alternatives you've considered**
No alternate available.

**Additional context**
Screenshot attached for reference.
![Cashew Import - Google Sheets Template](https://github.com/jameskokoska/Cashew/assets/67775802/a3004dd8-647f-493c-a275-c55324bc85e1)

Thanks. I really loved the app.
Keep going. :)

**Comment by jameskokoska** [comment] 2024-02-08 20:30
Duplicate of https://github.com/jameskokoska/Cashew/issues/87

**Closed by jameskokoska** 2024-02-08 20:30 UTC
Labels: enhancement

**Comment by ngocanhtve** [comment] 2024-02-09 01:27
Suggest you a way to import as follows:

- The main categories will be named for example A.
- The subcategories of A will be named for example A-xyz.
- Import everything into Cashew.
- Go to the categories which named start with “A-” to convert it to a subcategory of A. All transactions will be converted.
![](https://i.imgur.com/TlBMUNC.png)
- Good luck!
