### ISSUE TITLE
Multicurrency improvement

### ISSUE THREAD

**Issue by krzemyczek** [jameskokoska/Cashew#44] opened 2023-11-22 18:07 UTC
Hi again. 
So I notice some leaks of multicurrency functionality. It is:

- adding goals in different currency. (Use case: saving money in different currency for worst-case scenario in your country or just for foreign trip)

- adding option to transfer money by different currency (it is: I exchange in revolut euro(€) into 10 dollars($) . And it is not obvious how much euros it was. In screenshot how it works in revolut and what i mean.
![IMG_20231122_190136](https://github.com/jameskokoska/Cashew/assets/81762967/958c00fc-fc32-48d8-b6a9-145cc99f9149)
  And what important, price should be exchange by the day of transaction (if possible)

- Something off topic but it would be nice to has option to combine two transactions into transfer since after importing transactions every single transfer is seem as expensive and transfer, and editing every one of them is a really pain.

**Comment by jameskokoska** [comment] 2023-11-23 00:03
> Hi again. 
> So I notice some leaks of multicurrency functionality. It is:
> 
> - adding goals in different currency. (Use case: saving money in different currency for worst-case scenario in your country or just for foreign trip)
> 

Currency for goals and budgets is a duplicate of https://github.com/jameskokoska/Cashew/issues/29. Feature has been added already!

> - adding option to transfer money by different currency (it is: I exchange in revolut euro(€) into 10 dollars($) . And it is not obvious how much euros it was. In screenshot how it works in revolut and what i mean.

You can transfer money between different accounts already. If the accounts have different currencies, the amount will be converted accordingly. When you are transferring out you only see the primary currency. I feel like the UI will be too cluttered showing conversion of both. The user really only needs to know the amount they are transferring out of, which it already shows. 

> ![IMG_20231122_190136](https://github.com/jameskokoska/Cashew/assets/81762967/958c00fc-fc32-48d8-b6a9-145cc99f9149)
>   And what important, price should be exchange by the day of transaction (if possible)
> 
> - Something off topic but it would be nice to has option to combine two transactions into transfer since after importing transactions every single transfer is seem as expensive and transfer, and editing every one of them is a really pain.

Not sure I understand this final one. If referring to transfers, a transfer is 2 transactions because one is a transfer out and one is a transfer in. If they were merged, it would be a transaction equivalent to 0 which is meaningless.

**Closed** 2023-11-23 00:04 UTC

**Comment by krzemyczek** [comment] 2023-11-23 12:50
> If they were merged, it would be a transaction equivalent to 0 which is meaningless.

I meant change two transactions into transfer, by select two transactions

![Screenshot_2023-11-23-07-32-48-66_e6824bb696bab290a098ced1b814527d](https://github.com/jameskokoska/Cashew/assets/81762967/d60fbcc5-37c1-498d-b559-ebf541df5738)
 I
 I
V
![IMG_20231123_134941](https://github.com/jameskokoska/Cashew/assets/81762967/14cda1e8-b7f6-4f02-b18d-436a3711db5e)

**Comment by krzemyczek** [comment] 2023-11-23 13:55
> Thanks for the clarification. You can already do this by selecting both transactions and selecting the three dot menu, change category

Tkanks! I didn't notice
