### ISSUE TITLE
[Question] FDroid Integration

### ISSUE THREAD

**Issue by imcmjha** [jameskokoska/Cashew#301] opened 2024-06-23 07:17 UTC
Is there any plan to add this app to FDroid?

**Comment by ngocanhtve** [comment] 2024-06-23 07:22
You can use Obtainium to manage app installation and updates from Github release sources.
FYR: https://github.com/imranr98/obtainium/

**Comment by jameskokoska** [comment] 2024-06-23 07:42
Duplicate of #201 #111 #82

**Closed** 2024-06-23 07:42 UTC
Labels: question

**Comment by Thewisem** [comment] 2024-06-28 09:04
How is this completed?
