### ISSUE TITLE
[Feature Request] Recurring schedule transfer

### ISSUE THREAD

**Issue by fakesimo** [jameskokoska/Cashew#424] opened 2024-09-16 07:20 UTC
**Is your feature request related to a problem? Please describe.**
Every month I have some auomatic transfers pf Money between bank accounts, so a feature that allow the user to schedule transfers of money would be great, in a way to avoid every month tò inserti the same operation

**Describe the solution you'd like**
The possibility to set a "scheduled" transfer every month, like the subscription function that Is already present

**Describe alternatives you've considered**
Setting up a monthly reminder on my phone to insert the transfer operations every month

**Comment by fakesimo** [comment] 2024-09-16 07:44
It can work! Thanks! 😄

**Comment by Anu6is** [comment] 2024-09-16 11:41
This feature already exists without the `Subscription` workaround. 
You can simply create a `Transfer` transaction, mark it as `Repetitive` and set the desired `Period`

**Comment by justinmahendra** [comment] 2024-09-16 11:46
I feel dumb now. You can't create it from (+) button directly.

**Comment by justinmahendra** [comment] 2024-09-16 11:49
Probably needs a UI fix. Transfer doesn't return to first UI? Need to mark it as repetitive before clicking "Transfer"

**Comment by jameskokoska** [comment] 2024-09-16 12:39
Duplicate of https://github.com/jameskokoska/Cashew/issues/160

**Closed by jameskokoska** 2024-09-16 12:39 UTC
Labels: enhancement
