### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by rokso** [jameskokoska/Cashew#190] opened 2024-03-22 18:37 UTC
**Describe your question**
In the market of budget tracking and transaction tracking apps, many users choose to go with the app which has integration with financial institutions. So I am just curious to know, how hard is it to add this option? If integration with a cost then maybe make it a premium feature?

**Comment by jameskokoska** [comment] 2024-03-22 18:41
Duplicate of https://github.com/jameskokoska/Cashew/issues/33

**Closed by jameskokoska** 2024-03-22 18:41 UTC
Labels: question

**Comment by rokso** [comment] 2024-03-22 19:43
I tried scrolling through closed issues but couldn't find one. Thanks for this and for all the work you have put into the app.
