### ISSUE TITLE
[Feature Request]: Automated recalculate for budget

### ISSUE THREAD

**Issue by 666f78** [jameskokoska/Cashew#282] opened 2024-05-29 19:20 UTC
**Is your feature request related to a problem? Please describe.**
Need to recalculate sum every month for budget. I wanna spend 80% of income

**Describe the solution you'd like**
Add a feature to the budget that will look at incoming funds and recalculate the percentage

Income sum × 0,8 = sum for expense budget

**Comment by jameskokoska** [comment] 2024-05-29 21:13
Duplicate of https://github.com/jameskokoska/Cashew/issues/198

**Closed by jameskokoska** 2024-05-29 21:13 UTC
Labels: enhancement
