### ISSUE TITLE
Account Forecast Balance based on recorded recurring transactions

### ISSUE THREAD

**Issue by Ahmed-Abosamaha** [jameskokoska/Cashew#390] opened 2024-08-24 09:07 UTC
Based on the recorded recurring/recpetitive transactions which are not paid yet , is there any way allow users to know the forecast/future  balance for any account  based a certain Future period in the future.

For example if one of the existing account it's current balance is $500 and there are two recurring transaction monthly related to this account , one of them $50 and the other one $10 
If I need to know the forecast balance for this account next three month, the application  will till me the forecast balance will be $680 

Please this case is not duplicated with #315

Please if you need further information let me know.

**Comment by jameskokoska** [comment] 2024-08-24 13:34
This is an exact duplicate of your previous issue #389. Please do not duplicate issues that have been already addressed.

**Closed by jameskokoska** 2024-08-24 13:34 UTC
Labels: question
