### ISSUE TITLE
[Feature Request] Recurring transfers

### ISSUE THREAD

**Issue by Beltarm** [jameskokoska/Cashew#415] opened 2024-09-10 18:06 UTC
**Describe the solution you'd like**
The very straightforward description: 
I would like to create a transfer that takes place every month, for example, just like incomes and outcomes

**Comment by jameskokoska** [comment] 2024-09-10 18:08
Duplicate of https://github.com/jameskokoska/Cashew/issues/160

**Closed by jameskokoska** 2024-09-10 18:09 UTC
Labels: enhancement
