### ISSUE TITLE
[Bug] adding entry adds title suggestion into main category not subcategory

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#520] opened 2024-11-17 10:54 UTC
As described in the title

**How to reproduce**
Add new entry then the title suggestion in the next time will be added to main category instead of subcategory

**Details**
 - Device: xiaomi note 10 pro
 - App Version: 5.4.4

**Comment by jameskokoska** [comment] 2024-11-17 14:57
Duplicate of https://github.com/jameskokoska/Cashew/issues/392

**Closed by jameskokoska** 2024-11-17 14:57 UTC
Labels: bug

**Comment by jameskokoska** [comment] 2024-11-17 14:59
Many of your GitHub issues have been duplicates. I am giving you a warning - as stated, make sure you do not duplicate issues.

**Comment by hexman1999** [comment] 2024-11-18 05:26
> Many of your GitHub issues have been duplicates. I am giving you a warning - as stated, make sure you do not duplicate issues.

I am sorry for that, but I always search for previous issues before I post but maybe keywords I use didn't show the issue I post is already posted, propably I have to search manually although lots of posts, 

I really loved the app and appreciate your work, I used many money managers before but this one is really fantastic, I only wanted to get the app improved more and more

Good luck bro, and I am sorry again
