### ISSUE TITLE
[Feature Request] Ability to import subcategory via csv

### ISSUE THREAD

**Issue by chupro** [jameskokoska/Cashew#492] opened 2024-11-01 03:54 UTC
**Is your feature request related to a problem? Please describe.**
Make it possible to import subcategories in a csv file. Thank you.

**Comment by jameskokoska** [comment] 2024-11-01 04:13
Duplicate of https://github.com/jameskokoska/Cashew/issues/87

**Closed by jameskokoska** 2024-11-01 04:13 UTC
Labels: enhancement
