### ISSUE TITLE
[Feature Request] Forecasting and Account Balance after each transaction incl. upcomming

### ISSUE THREAD

**Issue by annykyforu** [jameskokoska/Cashew#541] opened 2024-12-02 16:34 UTC
**Is your feature request related to a problem? Please describe.**
I would like to not only allocate the Budget and track Expenses but also would like to make planning ahead.
A feature to see Balance after each transaction incl. upcoming is highly aprreciated.

**Describe the solution you'd like**
For example, I want to know how buying x or y is going to affect my balance in the long-term and if I can actually do more with my money. So if I can see that even with all these expenses, I still have £1,000 extra by June... I can then decide to increase my savings now or I'm allowed to plan a holiday or I can buy an item that is more expensive but higher quality because I know I can afford it. I want to see different scenarios that are realistic.

Hope it makes sense.

**Describe alternatives you've considered**

![onlinebanking](https://github.com/user-attachments/assets/ae6bc660-d70f-4260-a3ac-2f609c494570)

**Comment by jameskokoska** [comment] 2024-12-02 16:37
Duplicate of https://github.com/jameskokoska/Cashew/issues/315

**Closed by jameskokoska** 2024-12-02 16:37 UTC
Labels: enhancement
