### ISSUE TITLE
Add a feature to account for interest rate in loan section

### ISSUE THREAD

**Issue by jegannathanmaniganadan** [jameskokoska/Cashew#232] opened 2024-04-20 18:45 UTC
Hello, 

Thanks a ton for writing this application, it is one of the best expense application I have used so far. I do have a small feature request where I would like to see Cashew to be able to account interest amount that every loan carries. 

This is something like a like, 

Total Loan amount : 1,00,00,000 INR
Interest Rate : 9%
Monthly Emi as a transaction : 75,000%
Any down payment as a transaction : some x amount

Based the monthly emi, interest rate and depending the one time down payment, it would be nice if the app can re-calculate/update the loan amount. This would be a useful feature for me personally.

**Comment by jameskokoska** [comment] 2024-04-20 18:48
Duplicate of https://github.com/jameskokoska/Cashew/issues/182

**Closed by jameskokoska** 2024-04-20 18:49 UTC
Labels: enhancement
