### ISSUE TITLE
[Feature Request] Adding multiple subcategories or budgets to a single transaction

### ISSUE THREAD

**Issue by rasot71** [jameskokoska/Cashew#495] opened 2024-11-06 21:42 UTC
Hello! Wonderful app! Congratulations! I started using it a few weeks ago and maybe I am not familiar with it yet, so I apologize for suggesting something that may already exists! I mainly use Cashew on PC. I migrated from CoinKeeper which is almost abandoned by the developer company...

I am considering that it would be useful to be able to assign multiple subcategories or budgets to a single transaction.

**Additional context**
For a example, I have an income from my "remote" job A for a project i worked on. So i would like to assign category "Salary" and 2 subcategories. Subcategory "job A" and subcategory "Project A". 
I think it would be useful, because that way the income would be visualized properly in the pie chart, in the "all spending" tab.

Another example would be a trip to Paris with my best friend. I could assign budget "Paris" and budget "Best Friend". Both budgets to all the transactions I make in Paris. That way I will know how much I spent with my best friend this month, in general, at my home town and Paris, but also how much i spent with him in Paris separately.

Thank you in advance!

**Comment by jameskokoska** [comment] 2024-11-06 21:44
Duplicate of https://github.com/jameskokoska/Cashew/issues/483

**Closed by jameskokoska** 2024-11-06 21:44 UTC
Labels: enhancement
