### ISSUE TITLE
 Add Option to Hide Specific Accounts

### ISSUE THREAD

**Issue by RijoKsd** [jameskokoska/Cashew#524] opened 2024-11-19 06:55 UTC
**Description**
In the current version of Cashew, all accounts are always visible to the user. To enhance privacy and usability, we request the implementation of a feature that allows users to hide specific accounts, such as a salary account, when they only want to focus on certain accounts like expense accounts.

**Proposed Feature Details:**

- Introduce a "Hide Account" option in the account settings or details page.
- Hidden accounts should not appear in the main account summary or reports but remain securely stored.
- Provide a toggle or filter to display hidden accounts if needed.
- Ensure users can re-enable visibility for hidden accounts anytime.

**Use Case Example:**
A user wants to focus solely on their expense account and hide their salary account details for clarity and privacy during certain reviews.

**Benefits:**
- Improves focus by allowing users to display only relevant accounts.
- Enhances privacy by hiding sensitive account details on demand.
- Provides better usability for users managing multiple accounts.

**Comment by jameskokoska** [comment] 2024-11-19 12:58
Duplicate of https://github.com/jameskokoska/Cashew/issues/265

**Closed by jameskokoska** 2024-11-19 12:58 UTC
Labels: enhancement
