### ISSUE TITLE
Attachments Saved Offline

### ISSUE THREAD

**Issue by usyboi** [jameskokoska/Cashew#273] opened 2024-05-19 10:29 UTC
Can there be an option to allow attachments to saved offline, just in a offline folder or maybe something like a syncthing folder , I don't want to use or rely on a cloud service?

**Comment by jameskokoska** [comment] 2024-05-19 13:36
Duplicate of https://github.com/jameskokoska/Cashew/issues/266

**Closed by jameskokoska** 2024-05-19 13:36 UTC
Labels: enhancement
