### ISSUE TITLE
[Feature Request] Transaction link with another transaction

### ISSUE THREAD

**Issue by rasot71** [jameskokoska/Cashew#549] opened 2024-12-08 14:57 UTC
This thought may be a little complicated to be implemented.

I think that it would be helpful to be able to link transactions.
More specifically, let's say that you pay 10eur and after a few weeks you receive a refund for whatever reason. Personally, I don't like to just delete the transaction or deselecting the option at the bottom "include amount", which is real nice and helpful in some occasions. 

![image](https://github.com/user-attachments/assets/689beecd-c62b-428d-9d7f-9483085cff23)

So, what I choose to do is to add the refund as a separate income (separate category). At that moment, it would be perfect to be able to correlate the first transaction. Something like a shortcut, that you can click or hover and see the details of the original transaction, like the amount, title, notes, date.
Another, alternative would be to add the option for every transaction for a refund. I attach a screenshot to let you know my thought of that alternative.

![image](https://github.com/user-attachments/assets/5bb01247-ed74-48c6-9275-6cbf15c9c047)

With that options underneath you will be able to select if you received a refund (in full or partial, and if partial enter the exact amount) and to which account (sometimes a refund is given to your IBAN and not debit card).

**Comment by jameskokoska** [comment] 2024-12-08 15:39
This is a direct duplicate of https://github.com/jameskokoska/Cashew/issues/545

**Closed by jameskokoska** 2024-12-08 15:39 UTC
Labels: enhancement
