### ISSUE TITLE
[Feature Request] Custom google drive location for sync

### ISSUE THREAD

**Issue by contact-maximux** [jameskokoska/Cashew#375] opened 2024-08-14 09:33 UTC
If I could do that. I can share my data with other user and two user can use cashew with sync. If I am wrong please tell me way how to use it between friends

**Comment by jameskokoska** [comment] 2024-08-14 13:08
Duplicate of https://github.com/jameskokoska/Cashew/issues/61

**Closed by jameskokoska** 2024-08-14 13:08 UTC
Labels: enhancement
