### ISSUE TITLE
[Feature Request] Ability to change currency for an expense

### ISSUE THREAD

**Issue by SMRehan96** [jameskokoska/Cashew#351] opened 2024-07-29 09:56 UTC
Right now, if i making an expense, i can only use the currency linked to that account but there are some expenses that can be in other currencies. For a one time expense, its not an issue as we can convert the amount and add it but most subscription payments are made in USD so their actual price might be different each month if the account is not in USD or a USD pegged currency. 
it would be convenient to make expenses in other currencies and the app automatically converts it to the account’s currency.

**Comment by jameskokoska** [comment] 2024-07-29 13:01
Duplicate of https://github.com/jameskokoska/Cashew/issues/109

**Closed by jameskokoska** 2024-07-29 13:01 UTC
Labels: enhancement

**Comment by SMRehan96** [comment] 2024-07-29 19:12
I dont think this serves the same purpose. I want the conversion to happen at very recurring payment, not just one time.
