### ISSUE TITLE
[Feature Request] Collect loan repayment to a separate account

### ISSUE THREAD

**Issue by se16n** [jameskokoska/Cashew#456] opened 2024-10-04 10:31 UTC
**Is your feature request related to a problem? Please describe.**
I lent money to someone, for example, through a bank transfer. Then I received the repayment in cash.

Currently, it is only possible to deposit the money I lent into the same account from which the loan was issued.

**Describe the solution you'd like**
1. When the "Collect" button is pressed, a list of accounts is displayed.
2. The user selects the account they want the repayment to be deposited into.

**Comment by jameskokoska** [comment] 2024-10-04 13:06
Duplicate of https://github.com/jameskokoska/Cashew/issues/350

**Closed by jameskokoska** 2024-10-04 13:06 UTC
Labels: enhancement
