### ISSUE TITLE
[Question]Adding operations via SMS from the bank

### ISSUE THREAD

**Issue by BorduhayEO** [jameskokoska/Cashew#566] opened 2024-12-29 22:15 UTC
Is it planned to add to the application analyzer SMS messages, which when paying by bank card and receiving sms from the bank would offer in automatic mode to add the operation expense / income and all that is associated with it?
Many financial apps are convenient with this feature because you don't have to manually enter everything, but the app analyzes receipts/deposits for you, checks the history of similar payments and pulls up the category and amount.

**Comment by jameskokoska** [comment] 2024-12-29 22:31
Direct duplicate of https://github.com/jameskokoska/Cashew/issues/205

**Closed by jameskokoska** 2024-12-29 22:31 UTC
Labels: question
