### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by vilchu** [jameskokoska/Cashew#569] opened 2024-12-31 00:15 UTC
Love the app, just a few suggestions ^^
First, add a bank card availability, like it's connected to the bank, so if I pay with my card, it also automatically removes the amount of money that I paid with from my bank balance

because I want to know If I'm paying with card, or just straight from the bank 😅

Second, Add a currency converter when adding new entry, as in if I'm abroad and it's in different currency, it'll automatically remove the amount of my currency from the bank 

Thank you for your consideration, and happy new year ^^

**Comment by jameskokoska** [comment] 2024-12-31 01:27
Duplicate of https://github.com/jameskokoska/Cashew/issues/205 and https://github.com/jameskokoska/Cashew/issues/109

**Closed by jameskokoska** 2024-12-31 01:27 UTC
Labels: enhancement
