### ISSUE TITLE
[Feature Request] Allow account transfer to be scheduled

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#332] opened 2024-07-17 06:46 UTC
**Is your feature request related to a problem? Please describe.**
As recommend in the Cashew [wiki](https://cashewapp.web.app/faq.html#track-credit-spending), For managing the credit card, I've created an account named CC. During the month I keep adding transactions to it as expected. Once the billing cycle ends, I get a statement for Total Amount Due. I want to schedule the account transfer in the same way as we currently schedule expenses OR income. This way I've the visibility of when the bill is due. And can mark it as paid on the desired date. Currently the transfer shows two future transactions :
1. CC transfer In &
2. Main account transfer out
This is not indicating that I still need to settle this bill. Also if the actual transaction date differs then will need to delete/modify date in both balance correction entries. At this point I may simply add the transfer entry directly while bill payment only.

**Describe the solution you'd like**
A simple ability to schedule the account transfer similar to expenses.

**Describe alternatives you've considered**
1. Add transfer entry simply while making the payment. But I'll lose out on the reminder etc & will need to track separately when the bill is due. 
2. Create a loan and schedule the expense of repayment of loan from main account. But can't use loan as an account while making entry for purchase transaction.
3. Make one expense scheduled entry in Main account and other income entry in CC. But will need to make sure to exclude these both from budgets etc. also if payment is made on any other date then need to modify dates in both. 

**Additional context**
I feel this is a basic use case and supporting an inbuilt straightforward solution will improve the UX.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not! duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-07-17 11:28
Duplicate of https://github.com/jameskokoska/Cashew/issues/160

This is already possible. A tutorial for repetitive and upcoming transfers is outlined in the FAQ https://cashewapp.web.app/faq.html#transferring-between-accounts

**Closed** 2024-07-17 11:28 UTC
Labels: enhancement

**Comment by Akv2021** [comment] 2024-07-17 13:04
Thanks for the revert. 
While I'm able to change the transfer transactions to upcoming, but it seems it's not getting included in upcoming tab of the scheduled section.
![Uploading Screenshot_2024-07-17-18-33-35-57_e6824bb696bab290a098ced1b814527d.jpg…]()

**Comment by Akv2021** [comment] 2024-07-18 04:03
@jameskokoska Any workaround for showing the scheduled transfer in total upcoming since otherwise it does not represent the scheduled transaction correctly

**Comment by jameskokoska** [comment] 2024-07-19 14:53
The upcoming total is correct; A transfer in of 900 and a transfer out of 900 has a net of 0. The scheduled transfer behaves like all other upcoming transactions.

**Comment by Akv2021** [comment] 2024-07-21 04:59
Is there a way to get an indication on the home page that the main account indeed has an upcoming deduction ?

**Comment by Akv2021** [comment] 2024-07-23 14:48
@jameskokoska ?

**Comment by shackra** [comment] 2024-07-28 01:28
> The upcoming total is correct; A transfer in of 900 and a transfer out of 900 has a net of 0. The scheduled transfer behaves like all other upcoming transactions.

Indeed, the net result of subtracting X from 1 account and adding X to another account is 0, but then the coming totals are incorrect by X:

![imagen](https://github.com/user-attachments/assets/490b1f1a-e811-4ea0-91ce-382528660e6f)

In fact, I had to subtract 195,997 CRC from the amount above to get a better estimate of how much money I'll have left for the coming period.
