### ISSUE TITLE
Actual archive and management of lots of loans

### ISSUE THREAD

**Issue by imericxu** [jameskokoska/Cashew#542] opened 2024-12-02 18:06 UTC
# Description

The more loans you make the more cluttered it gets. “Hidden” loans still get in the way, and because new loans are added to the bottom of the list, you have to scroll past all the previously “hidden” loans to get to them. Hidden loans also still show up on the new transaction page, but grayed out, so if you want to quickly create a new loan, you have to scroll past all the hidden loans.

# Proposed Solution

- A separate archive tab for loans
- Option to auto-archive completed loans or have a pop up that asks if you want to archive on completion
- Keep the current implementation, just add new loans to the top of the list instead and hide hidden loans on the new transaction page.

# Alternatives/Hacks

Not using loans and creating categories for “Loan” and “Paid Back,” then filtering them out when needed.

# Additional Context

I just started using this app yesterday, and this might not be the intended use of loans, but I like being able to categorize situations like temporarily paying for somebody’s food as not my own expense.

The following screenshots show the issues described above:

| <img src="https://github.com/user-attachments/assets/65b06aea-4f15-4119-a166-dfad1e8cc370" alt="Hidden loans on new transaction page" width="200" /> | <img src="https://github.com/user-attachments/assets/39b463ca-3321-45f8-abce-dc35f1f905e8" alt="Loans Edit List" width="200" /> |
|--------|--------|

**Comment by jameskokoska** [comment] 2024-12-02 18:08
Duplicate of https://github.com/jameskokoska/Cashew/issues/260

**Closed by jameskokoska** 2024-12-02 18:08 UTC
Labels: enhancement

**Comment by imericxu** [comment] 2024-12-02 18:14
Oh that’s like exactly the same issue, my bad.
