### ISSUE TITLE
[Feature Request] Exclude from report option

### ISSUE THREAD

**Issue by arifszn** [jameskokoska/Cashew#203] opened 2024-03-30 18:50 UTC
**Is your feature request related to a problem? Please describe.**
When I correct my balance, it's automatically going to `Exclude from report` items (It does not show up on spending list). Maybe I don't want to exclude it. Vice versa, for a transaction, I might want to add this transaction to not show up in the reports.

**Describe the solution you'd like**
An option to mark `exclude from report` when doing a transaction.

**Describe alternatives you've considered**
Initially I thought `exlude amount` is the requested feature, but unfortunately it does not reflect the total amount if I exclude an amount.

**Additional context**
Moneylover has this feature. This is the only feature that is keeping me from switching to your amazing app.

![image](https://github.com/jameskokoska/Cashew/assets/45073703/72976002-56ef-41bf-bc2e-06069d790451)

**Comment by jameskokoska** [comment] 2024-03-30 19:22
Unfortunately the way the 'Balance Correction' category works, it will not count towards category totals. It is the way this category is implemented. If you need a transaction to count towards totals, you can create another category to replicate the balance correction one. 

Cashew already has a way to exclude amounts in reports. By setting 'Include Amount' to 'Off' it will make a transaction not count towards totals. To access this, edit a transaction, scroll down, tap [More Options] and you will see the option to 'Include Amount'. See screenshot.

![Screenshot_20240330_152153.png](https://github.com/jameskokoska/Cashew/assets/50821962/5e31c313-4686-4555-83b8-f608f52100e0)

**Comment by jameskokoska** [comment] 2024-03-30 19:22
This is a duplicate of https://github.com/jameskokoska/Cashew/issues/172

**Closed by jameskokoska** 2024-03-30 19:22 UTC
Labels: enhancement

**Comment by arifszn** [comment] 2024-03-30 22:40
`setting 'Include Amount' to 'Off' it will make a transaction not count towards totals.`

Similar to some other financial apps, I needed to have a transaction count against the total but not show up in the analytics. Turning off 'Include Amount' indeed prevents it from showing up in analytics, but it also gets excluded from the total. It's not the same feature.

**Comment by jameskokoska** [comment] 2024-03-30 22:45
Thanks for the clarification! Unfortunately, this is quite a confusing user interaction and can create user confusion. Because of that reason, it will not be implemented.

**Comment by arifszn** [comment] 2024-03-30 22:49
Additional context: why this feature is important:
Transferring an amount from one account to another is considered as spending in the source account. But in reality, it's just a deduction of the total without considering spending.

When I see a report of the spending of a month, there are some false positive amounts of transfer transactions.

**Comment by jameskokoska** [comment] 2024-03-30 22:52
The balance correction category handles this use case. Unfortunately, including some balance correction transactions in some totals still isn't an intuitive usability feature.
