### ISSUE TITLE
[Feature Request] Auto read SMS message

### ISSUE THREAD

**Issue by selvamsivakumar** [jameskokoska/Cashew#388] opened 2024-08-23 09:26 UTC
**Is your feature request related to a problem? Please describe.**
Whatever I buy, I always make payments through the tap-and-pay option (NFC), even for a small amount. So, I will have many transactions in a day. Sometimes, I miss adding all the expenses in a day. It would be better if the app had a feature to read the SMS in a configured way to add the expense or income automatically. This would be more useful for people like me who want to make more transactions using cards, NFC, UPI, etc.

**Describe the solution you'd like**
The app should have a feature to auto-detect the expense or income from the SMS. It should be configured. All banks use their SMS structure to notify customers about the credit or debit transactions made in their accounts. The app should allow the user to configure what to read and how to be added to the transactions.

**Describe alternatives you've considered**
- Auto read SMS (should have the option to configure what to read from the SMS text content)
- Pop up to ask the user permission to add the information from SMS.

**Additional context**
-

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-08-23 12:23
Duplicate of https://github.com/jameskokoska/Cashew/issues/205

**Closed by jameskokoska** 2024-08-23 12:23 UTC
Labels: enhancement
