### ISSUE TITLE
[Feature Request] Overflowing Budget into the next budget reset

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#411] opened 2024-09-09 04:20 UTC
**Is your feature request related to a problem? Please describe.**
Imagine I have a 200$ weekly budget but for this week I found this very cool thing that I wanna buy but if I do my budget will overflow, I want to make that up buy reducing my upcoming week’s budget.

**Describe the solution you'd like**
An option for budgets to “overflow” or “underflow” into their next budget instance. So if I had spent 300$ on my previous week, the next week budget would already have 100$ spent

**Describe alternatives you've considered**
Currently I just keep this in mind when spending that I’ve overspent on the previous budget.

**Comment by jameskokoska** [comment] 2024-09-09 04:23
Duplicate of https://github.com/jameskokoska/Cashew/issues/134

**Closed by jameskokoska** 2024-09-09 04:23 UTC
Labels: enhancement
