### ISSUE TITLE
[Feature Request] First day of the week

### ISSUE THREAD

**Issue by pijanowskim** [jameskokoska/Cashew#325] opened 2024-07-09 07:09 UTC
**Is your feature request related to a problem? Please describe.**
In the calendar (when, for example, choosing the date of a transaction), the week starts on a Sunday instead of Monday.
The same happens with the heatmap, the first day is Sunday (on the android app, in the web app this behaves very weirdly)

**Describe the solution you'd like**
Preferably an option to choose the first day of the week; in the event that's impossible - have the week start on a Monday (as is standard in Europe, at least) or follow the locale of the device.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by ngocanhtve** [comment] 2024-07-09 11:19
> have the week start on a Monday (as is standard in Europe, at least)
My phone has Vietnamese language, and the first day of the week in Cashew's calendar is Monday. Depends on your system calendar.

**Comment by pijanowskim** [comment] 2024-07-09 11:23
> [ngocanhtve](/ngocanhtve)

My phone (and PC, for that matter) are both set to British English, which should use Monday as the first day of the week by default (as also evidenced by other apps using Monday as the first day of the week when set to use the locale default) and Cashew seems to be ignoring this. Perhaps this is a bug, but I still think it'd be best if this could be set by the user manually.

**Comment by ngocanhtve** [comment] 2024-07-09 11:31
> are both set to British English, which should use Monday as the first day of the week by default

I tried selecting English to watch, Sunday came first.

**Comment by jameskokoska** [comment] 2024-07-09 11:45
Duplicate of https://github.com/jameskokoska/Cashew/issues/67

**Closed by jameskokoska** 2024-07-09 11:45 UTC
Labels: enhancement

**Comment by pijanowskim** [comment] 2024-07-09 11:49
Should I open an issue as a bug report, then? #67 is supposed to be fixed by having the app follow the device locale, but that's not what's happening. Even after changing the device locale to English - Ireland which is supposed to only use Monday as the first day of the week the first day of the week in the app is still Sunday.

**Comment by jameskokoska** [comment] 2024-07-21 23:37
It has been added so the heatmap homepage section can be customized with a weekday start as Sunday or Monday if it differs from the default derived from the locale
Added here: https://github.com/jameskokoska/Cashew/commit/f280ba423bb202a615c413e683b9ae2c97be58d7
