### ISSUE TITLE
[Feature Request] Negative amount in transactions or other way to enter refunds

### ISSUE THREAD

**Issue by katrikm** [jameskokoska/Cashew#562] opened 2024-12-26 14:56 UTC
Hello I would like to be able to enter negative amount in transactions mainly because of entering credit notes and refunds.
The point is that I don't want refunds or credit notes to be added to my income but I want them to be deducted from my expenses.
Thank you

**Comment by jameskokoska** [comment] 2024-12-26 17:15
Duplicate of #172

**Closed by jameskokoska** 2024-12-26 17:15 UTC
Labels: enhancement

**Comment by katrikm** [comment] 2024-12-26 19:06
Hello, thanks for a quick response.
I have read instructions in [#172](https://github.com/jameskokoska/Cashew/issues/172), but it does not cover every situation.
For example partial refunds or refund to another account.

In the country where I live, partial refunds are common. The seller does not have to refund shipping costs.

Example:
Original transaction - Amount: 110, Category: Shopping
Refund - Amount: 100, Category: Shopping

So I'd like to see that I spent $10 in the "Shopping" category

Is there any way to achieve this in Cashew?
