### ISSUE TITLE
[Feature Request] Access information from Cashew

### ISSUE THREAD

**Issue by amzon-ex** [jameskokoska/Cashew#563] opened 2024-12-27 02:35 UTC
Following https://github.com/jameskokoska/Cashew/issues/127, app links were implemented in Cashew - which are extremely helpful for automating addition of transactions. 

I would love to see this feature extended to extract information out of Cashew - like, for instance, the net worth, spending/income in a period and so on.

This could help, for instance, to make custom widgets in iOS displaying useful info like one could do by default in Android. Since it has been indicated in https://github.com/jameskokoska/Cashew/issues/148 that there is no plan to implement iOS widgets as of now, this would give one a way to do it if one wanted.

This is also not tied to a specific platform, so makes more sense to implement.

**Comment by jameskokoska** [comment] 2024-12-27 02:56
Duplicate of https://github.com/jameskokoska/Cashew/issues/99

**Closed by jameskokoska** 2024-12-27 02:56 UTC
Labels: enhancement
