### ISSUE TITLE
[Feature Request] Separate loan settlement transactions 

### ISSUE THREAD

**Issue by navaneethnpk** [jameskokoska/Cashew#382] opened 2024-08-21 18:36 UTC
**Is your feature request related to a problem? Please describe.**
There is option to choose a payment is lent or borrow. But the settlement is not saving/considering as a transaction. The respective account is being updated when you settle a loan (partially or completely). But there is no settle transactions. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.] You can make each settled/Collect as a new transaction. 

**Describe alternatives you've considered**
I am not using the loan feature. Instead I have two payment categories: lent and borrow in expense and income respectively. Then I make transactions with these categories.

**Comment by jameskokoska** [comment] 2024-08-21 21:08
Duplicate of https://github.com/jameskokoska/Cashew/issues/350

**Closed by jameskokoska** 2024-08-21 21:08 UTC
Labels: enhancement
