### ISSUE TITLE
[Feature Request] Add Label or Tags

### ISSUE THREAD

**Issue by muhammadfredo** [jameskokoska/Cashew#532] opened 2024-11-28 05:09 UTC
**Is your feature request related to a problem? Please describe.**
I would like to suggest a feature that allows users to add labels or tags to expenses. This feature would enable users to group expenses using tags in addition to the existing generic categories and sub-categories.

Use Cases:
- Travel Expenses: When recording multiple category expenses for flight tickets, hotels, foods, and drinks, users can tag these expenses as "Holiday in Bali", "Holiday in Tokyo", and "Holiday in Bangkok".
- Hardware Expenses: When buying items like hard drives, users can tag them as "Work" for Workstation or "Entertainment" for Media repository while using same category "Hardware/Computer".
- Software Expenses: When buying software users can tag "Work", "Hobby", or "Upscale" and still using same "Software" as category.

That way users able to see how much they spent for "Holiday in Bali" and maybe compare it to "Holiday in Tokyo" manually.
If users are freelancer, they can track "Work" label/tags expenses as well.

**Comment by jameskokoska** [comment] 2024-11-28 05:56
This is a direct duplicate of https://github.com/jameskokoska/Cashew/issues/107. Please do not duplicate issues.

**Closed by jameskokoska** 2024-11-28 05:56 UTC
Labels: enhancement
