### ISSUE TITLE
[Feature Request] Subscription Currency payment other than main currency

### ISSUE THREAD

**Issue by Vucko130** [jameskokoska/Cashew#209] opened 2024-04-04 03:11 UTC
Is your feature request related to a problem? Please describe.**
My main currency is BDT. But I have Netflix, Amazon Prime, Google One, Microsoft 365, Bitwarden, 1Password, etc. subscriptions. Now these subscriptions are not in BDT but in USD.

**Describe the solution you'd like**
Is there any way to choose a subscription payment currency other than my main currency?

**Comment by jameskokoska** [comment] 2024-04-04 03:13
Duplicate of https://github.com/jameskokoska/Cashew/issues/109 or create another account.

**Closed** 2024-04-04 03:13 UTC
Labels: enhancement

**Comment by ngocanhtve** [comment] 2024-04-04 03:14
App stores that handle payments usually also accept local currency, in my case VND. So actually this is not a big deal.

**Comment by Vucko130** [comment] 2024-04-04 03:19
> App stores that handle payments usually also accept local currency, in my case VND. So actually this is not a big deal.

Well, in my case, foreign transactions must be in currency other than BDT. If i want to pay subscriptions in BDT then card will be declined.

**Comment by ngocanhtve** [comment] 2024-04-04 03:23
> If i want to pay subscriptions in BDT then card will be declined.

So you pay in dollars using an e-wallet, right? Create a separate dollar account in Cashew for Netflix payments, like James's solution.

**Comment by Vucko130** [comment] 2024-04-04 03:30
> > If i want to pay subscriptions in BDT then card will be declined.
> 
> So you pay in dollars using an e-wallet, right? Create a separate dollar account in Cashew for Netflix payments, like James's solution.

I pay using my bank card. It pays the merchant in their currency, like USD or EUR, and deducts money from my bank account, which is in BDT. It's a dynamic currency card. It can pay in any currency and will deduct money from the main BDT currency.

**Comment by ngocanhtve** [comment] 2024-04-04 03:35
> It can pay in any currency and will deduct money from the main BDT currency.

That's it, the bank card already does the job of converting the exchange rate and you will always be charged money in BDT, so just record the transaction in BDT as usual, no need to worry about USD.
