### ISSUE TITLE
[Feature Request] Define a budget as a percentage of overall period income

### ISSUE THREAD

**Issue by GoTVm** [jameskokoska/Cashew#559] opened 2024-12-22 22:32 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Rather than having to hard-code the budget's maximum upon creation, I'd like to be able to create budgets with dynamic maximum, based on the income of the period I've selected (eg. income between November 10 and December 10).

**Describe alternatives you've considered**
Hard-coding the maximum and then doing the maths separately to see if I've actually gone over budget.

**Additional context**
None.

**Comment by jameskokoska** [comment] 2024-12-23 00:56
Duplicate of https://github.com/jameskokoska/Cashew/issues/198

**Closed by jameskokoska** 2024-12-23 00:56 UTC
Labels: enhancement
