### ISSUE TITLE
[Feature Request] Sync with WebDAV

### ISSUE THREAD

**Issue by itzTheMeow** [jameskokoska/Cashew#296] opened 2024-06-11 00:23 UTC
The ability to sync data with a webdav host would be useful for those who don't want to use google drive. It also doesn't limit you to a specific service as you can host your own server using whatever platform you wish.

**Comment by jameskokoska** [comment] 2024-06-11 01:04
Duplicate of https://github.com/jameskokoska/Cashew/issues/84

**Closed by jameskokoska** 2024-06-11 01:04 UTC
Labels: enhancement
