### ISSUE TITLE
[Feature Request] Add Lent Money Collection Date

### ISSUE THREAD

**Issue by rahulkhatri137** [jameskokoska/Cashew#354] opened 2024-08-02 08:47 UTC
**Is your feature request related to a problem? Please describe.**
When I have a transaction of Lent money, and I collect it back it just updates but there is no record of when it is collected.

**Describe the solution you'd like**
1. Add a collection date in transaction description.
2. Create a new transaction on collection date clearing the -ve of lent transaction like repetitive transactions.
3. The collected button can be updated to show collection date too.

**Additional context**
Screenshot attached
![IMG_20240802_141002](https://github.com/user-attachments/assets/6016052b-3c2b-4d3c-80ed-f066d2ba8167)

**Comment by jameskokoska** [comment] 2024-08-02 12:03
Duplicate of https://github.com/jameskokoska/Cashew/issues/350

**Closed by jameskokoska** 2024-08-02 12:03 UTC
Labels: enhancement
