### ISSUE TITLE
Streamlining Loan Repayment Across Accounts

### ISSUE THREAD

**Issue by zeradawit** [jameskokoska/Cashew#225] opened 2024-04-14 07:59 UTC
**Description**:
As a user of the Cashew app for a couple of months with more than 700 transaction, I appreciate the convenience it offers for managing loans. However, I’ve encountered a limitation when it comes to repaying loans using a different account. For example When I borrow money from someone using my #Cash account, there is currently no straightforward way to repay the loan directly from any other account. The existing process involves multiple steps, which can be misleading in my transaction history.

**Current Process**:
1. I settle the loan as if I'm repaying it in cash.
2. To correct my #Cash account balance, I transfer funds from my #commercial bank account to my #Cash account.

****Proposed Enhancement**:**
I recommend implementing a feature that allows users to repay loans directly from their preferred accounts. This enhancement would simplify the process, maintain accurate transaction records, and enhance overall user experience.

Thank you for considering this improvement, and I look forward to a more seamless loan repayment process in the Cashew app!

**Comment by jameskokoska** [comment] 2024-04-14 08:01
Duplicate of https://github.com/jameskokoska/Cashew/issues/106

**Closed by jameskokoska** 2024-04-14 08:01 UTC
Labels: enhancement

**Comment by ngocanhtve** [comment] 2024-04-14 08:04
Are you using the one-time loan type? It won't be possible to select an account when repaying a loan, and I've requested this feature for a long time but was denied. Fortunately, we can use the long-term loan type instead and select an account for repayment transactions in this type of long-term loan is possible.

**Comment by zeradawit** [comment] 2024-04-14 09:46
> Duplicate of #106

Here are other issues I found while following the method you mentioned in the comment earlier:

When I click the “partially settle” option for a one-time loan, it navigates me to the option to repay my loan with a different account. I found this to be a brilliant solution. However, there is a catch. Even if I settle my debt completely, a long-term loan will still be present in the new transaction template. I attempted to delete the transaction but, it rewrite the loan transaction as income (not a loan),  that’s not what I want. This issue persists even in a gole features also.

**Comment by zeradawit** [comment] 2024-04-14 09:57
> Are you using the one-time loan type? It won't be possible to select an account when repaying a loan, and I've requested this feature for a long time but was denied. Fortunately, we can use the long-term loan type instead and select an account for repayment transactions in this type of long-term loan is possible.

Thank you! It works perfectly. I hadn’t seen it for a long time, but there’s a catch. You can find it in my quote reply for the developer, and I’d appreciate it if you could let me know how you address the issue differently.

**Comment by ngocanhtve** [comment] 2024-04-14 11:01
> You can find it in my quote reply for the developer, and I’d appreciate it if you could let me know how you address the issue differently.

The issue will always be there. I ignore it, I don't want to delete settled loans because anyway I will review the loans again and again every time I need to look back. The fact that settled loans are still there helps us know their presence, so we can later let someone review the statistics if necessary.
