### ISSUE TITLE
[Feature Request] Google services seem to be mandatory to add attachments

### ISSUE THREAD

**Issue by atomiseur5533** [jameskokoska/Cashew#373] opened 2024-08-14 09:14 UTC
**Describe the bug**
When you try to attach a picture or a file to a transaction, the app display a "Connection error, verify your internet connection" message and there is a system notification about the Google services not being activated, and the app also freezes on a loading logo.

**How to reproduce**
You have to deactivate all Google services first and then try to add a file

**Screenshots/videos**
[Screenshots/videos are always helpful]

**Details**
 - Device: SM-G991B/DS (Galaxy S21 5G)
 - App Version: v5.3.4+396, db-v46
**Additional notes**
I understand that you are not willing to do any syncing outside of Google, but my understanding is that you wanted to make the app still working offline.

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment] 2024-08-14 13:04
Duplicate of https://github.com/jameskokoska/Cashew/issues/266

**Closed** 2024-08-14 13:04 UTC
Labels: enhancement
