### ISSUE TITLE
Add Credit Card as An Account and some extra suggestions

### ISSUE THREAD

**Issue by kumaratv** [jameskokoska/Cashew#414] opened 2024-09-10 11:41 UTC
Cashew's team is doing a great work in helping people manage their money, adding new features and improving the app, so here is my humble suggestions:-

(1.) • Add Credit Card option as an Account.
       • Where we can set Credit Card Allowed Limit.
       • Payment Due Date of the Card.

(2.) • Option to add gift cards as an account.

That's all I could suggest till now.

Thank you  very much for Creating this App. I am loving this app so much.

**Comment by jameskokoska** [comment] 2024-09-10 12:16
Duplicate of https://github.com/jameskokoska/Cashew/issues/124

**Closed by jameskokoska** 2024-09-10 12:16 UTC
