### ISSUE TITLE
[Bug] csv importing - date issue

### ISSUE THREAD

**Issue by domaesil** [jameskokoska/Cashew#231] opened 2024-04-17 21:20 UTC
**Describe the bug**
I'm not sure if i'm doing wrong, or it's a bug. But I've used the csv template correctly (dd/mm/yyyy hh:mm) but when imported, the dates are totally wrong. I've tried everything (changing the cells format from date, text, general, custom, etc.) but it's still showing the same 'wrong' dates.

**How to reproduce**
by importing csv files...? at least, the issue is consistent from my end.

**Screenshots/videos**
the csv file I used:
<img width="660" alt="image" src="https://github.com/jameskokoska/Cashew/assets/167365484/d558e632-a5c0-4dcd-99b9-7884c69da69e">

after importing:
<img width="594" alt="image" src="https://github.com/jameskokoska/Cashew/assets/167365484/09d4651e-55be-478b-92a0-bf52be910bb8">

**Details**
 - Device: MacBook Pro/ Sonoma 14.4.1
 - App Version: v5.2.9+353, db-v46

**Additional notes**
Thank you for your hard work!

**Comment by jameskokoska** [comment] 2024-04-17 23:37
This is a duplicate of: 
https://github.com/jameskokoska/Cashew/issues/193 and https://github.com/jameskokoska/Cashew/issues/25

Your dates may be set incorrectly. It seems like Cashew is flipping your date with the month. Please ensure the dates in your CSV follow proper date formats. Cashew tries many date formats to ensure data is correctly formatted, however it may not always select the correct format. You may need to enter a custom date format in Cashew so it understands the date format you are using when importing transactions from your CSV.  See screenshot. ![Screenshot_20240417_193507.png](https://github.com/jameskokoska/Cashew/assets/50821962/07a39ac6-2916-48b9-8195-3657095c2047)

**Closed by jameskokoska** 2024-04-17 23:37 UTC
Labels: bug

**Comment by domaesil** [comment] 2024-04-17 23:50
But as you can see in my screenshot, I'm following the correct date format from the provided template file.

I have also tried to enter a custom date format (the screenshot you uploaded), but it didn't work.

**Comment by jameskokoska** [comment] 2024-04-17 23:55
Can you please provide details on the CSV file you used and I can look into the issue?

**Comment by domaesil** [comment] 2024-04-17 23:57
The template I've downloaded:
[5349b199-2dd2-4f29-8ce8-f32960293321.csv](https://github.com/jameskokoska/Cashew/files/15018178/5349b199-2dd2-4f29-8ce8-f32960293321.csv)

The csv file I made accordingly:
[amex test.csv](https://github.com/jameskokoska/Cashew/files/15018179/amex.test.csv)

**Comment by jameskokoska** [comment] 2024-04-18 00:43
Thank you for the details! After analyzing both files, it does seem that there is a discrepancy between the template CSV and the provided CSV. See screenshots
![Screenshot_20240417_201649_HTML Viewer](https://github.com/jameskokoska/Cashew/assets/50821962/56dcfbc9-7eb3-4c11-95fc-98438894a8f4)
![Screenshot_20240417_201617_HTML Viewer](https://github.com/jameskokoska/Cashew/assets/50821962/d1af6b5a-2da3-4e53-a3e7-2e82837f9a8d)

Please ensure the use of the official supported CSV format or use a custom format. After testing, using a custom format of `dd/MM/yyyy  HH:mm` has worked for me on your provided CSV. Note that there are 2 spaces between `yyyy` and `HH`.

**Comment by domaesil** [comment] 2024-04-18 01:48
It's strange! This is how i see on my end (the template file):

<img width="129" alt="image" src="https://github.com/jameskokoska/Cashew/assets/167365484/8f5e7314-2656-4dd8-a628-4f3197373bba">

it's not 2024-04-17 13:38 as you see. What would have been causing the issue?

**Comment by jameskokoska** [comment] 2024-04-18 02:00
Depending on which Excel application you are using, it may display the formatted value over the actual value present. It usually does this for dates, times, and money.

**Comment by jameskokoska** [comment] 2024-04-22 00:36
CSV import has been improved to give a preview of the parsed datetime. Added here: https://github.com/jameskokoska/Cashew/commit/c59e8e9c8e5add163cf626d3ada7a568d4bffd0f

**Comment by kamranabbas20** [comment] 2025-05-19 16:16
Hi, I have been doing this for several times and it worked perfectly, but for some reason, it doesn't work as expected for the last couple of times. Here is and example of file I am trying to load.

[cashew-import-template issue testing.csv](https://github.com/user-attachments/files/20300613/cashew-import-template.issue.testing.csv)
