### ISSUE TITLE
[Feature Request] Support for 1. manual entry of currency exchange rates AND 2. multi-currency accounts 

### ISSUE THREAD

**Issue by Veethahavya** [jameskokoska/Cashew#187] opened 2024-03-20 18:17 UTC
1. Often, transactions from accounts of different currencies are pegged to a fixed exchange rate on the day. Therefore, it would be great if a local exchange rate for transfer between two accounts can be defined that is applicable only to the transaction.
2. 2. Many banks offer multi-currency acccounts. Support for this would be great!

**Comment by jameskokoska** [comment] 2024-03-20 18:27
You can change the currency exchange rate in Settings already. There are no plans to support at time currency conversion rates - at that point each transfer transaction should be edited individually after being created.

Unfortunately the way the database is designed, each account can only have one currency tied to it. Duplicate of #109. You can use in place currency conversions.

**Closed** 2024-03-20 18:28 UTC
Labels: enhancement
