### ISSUE TITLE
[Bug] Amount of Transactions Mismatch in all spendings page

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#380] opened 2024-08-20 10:04 UTC
**Describe the bug**
In the all spendings page, the net total shows a total amount of transactions that is different from the total if you add up the transaction amounts in the card below it.

**How to reproduce**
- Have many transactions of different type (loans, LTL, Balance corrections, Balance corrections associated with LTLs,
- Look at All Spendings Page

**Screenshots/videos**
![IMG_8383](https://github.com/user-attachments/assets/ea68e829-7c52-4346-b93b-4501968d734f)

The Balance correction here is due to the fact i transferred money from Account A to account B, but marked the "transfer out" transaction as a payment to an LTL, as shown below.
![image](https://github.com/user-attachments/assets/318529a2-935f-49d0-86ff-93b7aa18a104)

And it seems stuff like this is not added to the card. as when i click in the balance correction line, i dont see that transaction anymore.

Also. Lent Shows that there are 4 transactions, but when clicking on it, i see more than 4
![image](https://github.com/user-attachments/assets/ebc27dd3-3aca-40b8-b7ac-a8303c00b5d9)
![image](https://github.com/user-attachments/assets/a8de1580-d9c3-4d2f-8789-4af2596bb646)

**Details**
 - Device: iPhone 14 Pro
 - App Version: 5.3.8+410

**Additional notes**
This appears to be an error in the outside filter compared to the inside filter. In the case of loans, the outside filter says 4 at the total count, but the inside filter shows more. Unsure what the filters are and if they are accurate considering the numbers outside and inside are different and I cannot isolate which transactions it is talking about

**Comment by jameskokoska** [comment] 2024-08-20 13:15
Can you please provide a minimum reproducible example so I can further look into this issue? I am not able to replicate the issue.

You can also provide a copy of your data, however be mindful of sharing sensitive financial information.

**Comment by jameskokoska** [comment] 2024-08-21 04:14
The main issue here is that "Paid" transactions are not counted in the "All Spending Total Row" but when listed in the transaction search page, the count is all the transactions listed. Unfortunately, I think this discrepancy is always going to be the case. Once one time loans have been marked as paid, we don't want to count the transactions in the total count as they are already settled. This is to be consistent with the homepage loans widget as well.

There is some weird behaviour here, however, with Balance Corrections also being part of a short term loan not properly filtering out when on the Search page that I can look into. (i.e. the filter "No Loan" doesn't seem to be applied to also removing one time loans)

There is also another bug that selecting a history time period removed the totals for Loans, which was accidentally left from the previous version's logic. This created an incorrect net from adding all the totals in the rows, which is not the intended behaviour.

I will look into these related issues

**Comment by jameskokoska** [comment] 2024-08-22 04:28
Fixed here: https://github.com/jameskokoska/Cashew/commits/main/

**Closed by jameskokoska** 2024-08-22 04:28 UTC
Labels: bug
