### ISSUE TITLE
Cashew Pro without using Google Play

### ISSUE THREAD

**Issue by Zagur** [jameskokoska/Cashew#111] opened 2024-01-08 20:41 UTC
I don't use Google Play to install my apps as I prefer to use shops like F-Droid (have you thought about including this app there?). I really like the APP and would be interested in donating even some money. Is there no other way to buy the Pro version? Have you thought about using some other method outside Google Play?

**Comment by jameskokoska** [comment] 2024-01-09 21:36
Duplicate of https://github.com/jameskokoska/Cashew/issues/82

**Closed by jameskokoska** 2024-01-09 21:37 UTC
Labels: question
