### ISSUE TITLE
Github releases behind playstore ?

### ISSUE THREAD

**Issue by PitiBouchon** [jameskokoska/Cashew#538] opened 2024-12-01 23:52 UTC
The latest github releases is of version 5.3.4+396 while the current playstore version is 5.4.4. Why are guthub releases behind in version than the playstore one ? (that is usually the opposite)

**Comment by jameskokoska** [comment] 2024-12-01 23:56
Duplicate of https://github.com/jameskokoska/Cashew/issues/396

**Closed by jameskokoska** 2024-12-01 23:56 UTC
Labels: question
