### ISSUE TITLE
[Feature Request] Encrypted Google drive backup 

### ISSUE THREAD

**Issue by Ansem93** [jameskokoska/Cashew#133] opened 2024-01-31 23:29 UTC
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]
Since Cashew stores sensitive data, I would like to have the Google drive backup to be encrypted with a password. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Let us choose a password in order to encrypt the file. 
If it's not possible to do an incremental backup I'm fine. Cashew can create a new daily/weekly file 

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]
There is already an "export csv" and "export backup". Maybe you could ask if we want to encrypt it. 
Also I would love if you could Let us schedule the backup in a select folder on our phone, then we can choose how to handle it.

**Comment by jameskokoska** [comment] 2024-02-01 04:56
Duplicate of https://github.com/jameskokoska/Cashew/issues/20

**Closed by jameskokoska** 2024-02-01 04:56 UTC
Labels: enhancement
