### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Beerandoo** [jameskokoska/Cashew#498] opened 2024-11-07 19:32 UTC
**Is your feature request related to a problem? Please describe.** Yes, the problem I have is with how the current budgets work, they're best for salary workers who have a fixed monthly/yearly income, but not so much for hourly workers.

[A clear and concise description of what the problem is.
I find it difficult to budget a hourly based income when the current budgetting system asks for a fixed budget amount and that is hard to do because hours worked and potential bonuses/incentives changes frequently, making a base monthly income inaccurate.

**Describe the solution you'd like**
It would be extremely helpful if we could add a different budget option that allows for a variable monthly income. For example, if we were able to add how much each of our pay checks were as an income and instead of subtracting the amount spent that month it just increases the available budget. This would make budgetting to the penny an option making for more accurate budgets.

**Describe alternatives you've considered**
That's pretty much it, to be able to add maybe another budgeting option that allows for a variable monthly income which would help hourly workers as well.

**Comment by jameskokoska** [comment] 2024-11-07 19:34
Duplicate of https://github.com/jameskokoska/Cashew/issues/198

**Closed by jameskokoska** 2024-11-07 19:34 UTC
Labels: enhancement
