### ISSUE TITLE
[Feature Request] Add option to type entire amount, including cents

### ISSUE THREAD

**Issue by allanforms** [jameskokoska/Cashew#531] opened 2024-11-27 19:52 UTC
**Is your feature request related to a problem? Please describe.**
Personally, I think, as most of the expenses are broken in the cents units, it should be default behavior to type every number considering cents, not filling them with "00".
I can't type with a decimal properly: I'm a good typer, but I mess up with cents (dot/comma not always pressed when I type a transaction, across devices).
Besides, it improves the user experience, as the fill out process in the majority of transactions are specified to the units of cents.

**Describe the solution you'd like**
I want a option to type everything in the amount field, including the cents ($123,45: type "12345" instead of "123,45" or "123.45")

**Describe alternatives you've considered**
Keep as it is now by default, add the option to type the cents if someone wants it.

**Additional context**
Seems to me a more straightforward approach: the vast majority of transactions added are little expenses specified up to the cents, not rounded amounts like $123.00, but $123.45 instead. And if someone not like this behavior they can change it in the settings.

**Comment by jameskokoska** [comment] 2024-11-27 19:54
Exact duplicate of https://github.com/jameskokoska/Cashew/issues/440

**Closed by jameskokoska** 2024-11-27 19:54 UTC
Labels: enhancement

**Comment by allanforms** [comment] 2024-11-28 17:21
Sorry about that, I looked for similar feature requests only in the open issues, not the closed ones.
