### ISSUE TITLE
[Feature Request] Option to choose account when "Settle All" or "Collect All" Loan

### ISSUE THREAD

**Issue by tqdungctuct** [jameskokoska/Cashew#137] opened 2024-02-03 09:46 UTC
**Is your feature request related to a problem? Please describe.**
I would like to suggest a feature that allows users to choose which account to use when using the 'Settle All' or 'Collect All' option for loans. Currently, I can manually choose the account when using 'Partially Collect' or 'Partially Settle,' but the 'Settle All' or 'Collect All' option uses the original account by default.

**Comment by jameskokoska** [comment] 2024-02-03 09:53
Duplicate of https://github.com/jameskokoska/Cashew/issues/123

**Closed** 2024-02-03 09:54 UTC
Labels: enhancement
