### ISSUE TITLE
Some issues related to transaction details, etc.

### ISSUE THREAD

**Issue by pengweizhong** [jameskokoska/Cashew#245] opened 2024-04-30 01:04 UTC
Hello developer, this is my experience after using it recently. Generally speaking, this is a great software. From interaction to interface display, it is excellent. I can feel that it takes too much effort. Thank you developer for bringing it. Such excellent software. 

These words were translated using Google. They may be different from my original meaning, but they should be roughly the same. If you can understand Chinese, I have posted the original words at the end.

 The following is in no particular order… 

• Do not default the account category, because many times the default category is chosen directly because the category is ignored. It is recommended to specify it manually. 

• Categories should not be strongly bound to expenses. For example, I created a (online shopping) category, but refunds may occur, so the (online shopping) used for expenses may also be income, but it is allocated to expenses by default. So I have to revise it again every time, which is very troublesome. It is recommended that when creating a transaction, you can manually specify whether this is an expense or income 

• During the process of creating a transaction, there is no return operation. If a mistake was made in the previous step, it cannot be changed and can only be modified after saving. It is recommended to add the operation of returning to the previous step. 

• The credit card limit should not be included in the net worth, but it can still be used for consumer spending, and the amount after spending should be included in the net worth.

…………………………………………
…………………………………………
…………………………………………

以下内容不分先后顺序…

	• 账户类别不要默认，因为很多次因为忽略了选择分类而直接选择默认的分类了，建议手动指定。

	• 类别不应该和支入支出进行强绑定，比如我创建了（网购）分类，但是有可能会产生退费，因此用于支出的（网购）也有可能是收入，但是默认划给了支出，所以我每次都要再次修改，很麻烦。建议在创建交易时，能够手动指定这是支出还是收入

	• 创建交易的过程中，没有返回操作，如果上一步操作失误则无法变更，只能保存后再修改。建议增加返回上一步的操作。

	• 信用卡类的额度不应计算入净值中，但是它仍然可用于消费支出，支出后的金额应计入到净值中。

**Comment by jameskokoska** [comment] 2024-04-30 01:08
> • Do not default the account category, because many times the default category is chosen directly because the category is ignored. It is recommended to specify it manually.

I'm not sure I understand. All transactions require a category and the user can select any category.

> • Categories should not be strongly bound to expenses. For example, I created a (online shopping) category, but refunds may occur, so the (online shopping) used for expenses may also be income, but it is allocated to expenses by default. So I have to revise it again every time, which is very troublesome. It is recommended that when creating a transaction, you can manually specify whether this is an expense or income

All transactions require a category. Duplicate of https://github.com/jameskokoska/Cashew/issues/240

> • During the process of creating a transaction, there is no return operation. If a mistake was made in the previous step, it cannot be changed and can only be modified after saving. It is recommended to add the operation of returning to the previous step.

You can tap out and edit any changes manually. The initial entering of information is to increase speed of usage.

> • The credit card limit should not be included in the net worth, but it can still be used for consumer spending, and the amount after spending should be included in the net worth.

Duplicate of https://github.com/jameskokoska/Cashew/issues/92. This is also the case for net worth.

**Closed by jameskokoska** 2024-04-30 01:08 UTC
Labels: enhancement

**Comment by pengweizhong** [comment] 2024-04-30 02:06
> I'm not sure I understand. All transactions require a category and the user can select any category.  

Yes, this may be a problem with my operating habits. I like to manually specify the category every time because my consumption scenarios are relatively complex. There is no category that has the highest consumption scenario for me every day. Instead, I need to edit it again. correction, reducing efficiency.  


> All transactions require a category. Duplicate of https://github.com/jameskokoska/Cashew/issues/240. Additionally, you can select income/expense to your liking, it is not bound to a category. The category just sets the default/initial income/expense option selected.   
> You can tap out and edit any changes manually. The initial entering of information is to increase speed of usage.  

This may be due to my lack of understanding of the APP. I just discovered that it can indeed be modified when it is first created, but it is covered by a pop-up window and requires me to go back first. I think this is not good enough. The excessive encapsulation is not suitable for most users. If I need to modify expenses/income, then I have to go back first. Maybe we can avoid pop-up windows to guide users and display important information larger on the editing page. For example, we can make the title take up more space or highlight it.  


> Duplicate of https://github.com/jameskokoska/Cashew/issues/92. This is also the case for net worth.  

This solves some of my problems, which is great. For credit card accounts, it would be better if you can limit the credit limit. For example, my credit limit is 10,000, but I cannot spend more than this number, or it is okay to use the credit limit only as a display.

Scenarios such as consumption/transaction/finance are often very complex, and we certainly cannot cover all scenarios. This would be too much work, but if we can, I hope this can become a better APP.
If possible, please let me close the question.

**Comment by jameskokoska** [comment] 2024-04-30 02:13
> This may be due to my lack of understanding of the APP. I just discovered that it can indeed be modified when it is first created, but it is covered by a pop-up window and requires me to go back first. I think this is not good enough. The excessive encapsulation is not suitable for most users. If I need to modify expenses/income, then I have to go back first. Maybe we can avoid pop-up windows to guide users and display important information larger on the editing page. For example, we can make the title take up more space or highlight it.

Sorry, this is how the app is designed. It is created to allow users to efficiently create transactions with the basic information. Details can be edited simply by swiping away the initial add transaction workflow.

> This solves some of my problems, which is great. For credit card accounts, it would be better if you can limit the credit limit. For example, my credit limit is 10,000, but I cannot spend more than this number, or it is okay to use the credit limit only as a display.
> 
> Scenarios such as consumption/transaction/finance are often very complex, and we certainly cannot cover all scenarios. This would be too much work, but if we can, I hope this can become a better APP. If possible, please let me close the question.

Duplicate of https://github.com/jameskokoska/Cashew/issues/124. Please avoid duplicating issues that have already been addressed.

**Comment by pengweizhong** [comment] 2024-04-30 03:29
Well, I don't think this is efficient. It seems that I only need to return every time I create a transaction.

**Comment by pengweizhong** [comment] 2024-04-30 03:30
Well, I don't think this is efficient. It seems that every time I create a transaction, I can only go back first, cover up the pop-up window and continue the operation. . .

**Comment by pengweizhong** [comment] 2024-04-30 05:21
> Sorry, this is how the app is designed. It is created to allow users to efficiently create transactions with the basic information. Details can be edited simply by swiping away the initial add transaction workflow. 

Hi, I need to go back a bit each time, which is really painful. Is it possible to have a built-in button like [Quick Add] button, defaulted to TRUE, in which case it won't affect your original operating habits. But when I set it to FALSE, don't popup when creating a transaction. I'm begging to add this feature, I just added a few trades and it's really painful for me to force a popup every time I add!  

I just discovered a new logic problem, I just spent 50 on the platform when I bought groceries, and afterwards the platform refunded me 1.29 due to insufficient weight, so my actual expenditure should be (50-1.29=48.71). But I can't do this because there is no similar logic in Cashew, I can only delete the two transactions and re-add the new one: spent 48.71 on groceries. maybe when providing the [Include Amounts/Exclude Amounts] again, I can exclude some of the amounts or there is some other solution, thanks.

Translated with DeepL.com (free version)

**Comment by domaesil** [comment] 2024-05-28 19:01
Hi, I strongly agree with Pengweizhong, so I wanted to add on to it.

Regarding the 2nd point:

Yes, i know we can manually modify expense/income. But it's very inconvenient and inefficient. For example, I selected multiple transactions (Some of them were expenses, some were income), and edited the category. Then it changed ALL of them into expense which was the default of the category. So I've lost all info... I had to go back and change one by one... I don't want to create two categories for everything (like shopping/return, and health insurance payment/pay out, etc.) Only category that has solely one type is my paycheque category... I don't want to put all else into simply 'returned purchase'. This doesn't really reflect my spending habit and patterns. Could you please please change this...? I'm spending so much time trying to change everything back one by one...

**Comment by jameskokoska** [comment] 2024-05-28 19:15
You're correct in that large edits to transactions category should not change the polarity of the transaction amount. I will fix this workflow.
