### ISSUE TITLE
Viewing Balance at a Specific Point in Time

### ISSUE THREAD

**Issue by MohamedReda97** [jameskokoska/Cashew#315] opened 2024-07-02 09:12 UTC
Hi 

Thank you for your work on this expense tracker project. I have found it very useful for managing my finances. I have a feature request that I believe would enhance the functionality of the tracker.

Currently, the tracker allows me to log and view my expenses and incomes. However, I would like to be able to select a specific point in time and see my balance at that time. This would help me better understand my financial situation at various stages.

My Request:

Balance View at Specific Time: A feature that allows users to select a date or a point in time and see the balance (total money available) at that moment, considering all expenses and incomes up to that date.
I believe this feature would add significant value to the project, making it easier for users to track their financial progress over time.

Thank you for considering this request. I look forward to your response.

Best regards,

**Comment by ngocanhtve** [comment] 2024-07-02 11:17
Select net total in the Date Banner Total setting.

**Comment by MohamedReda97** [comment] 2024-07-02 11:19
> Select net total in the Date Banner Total setting.

I did, but it only shows me income and expense not total balance at that day I have selected

**Comment by jameskokoska** [comment] 2024-07-02 11:21
Duplicate of https://github.com/jameskokoska/Cashew/issues/58

**Comment by ngocanhtve** [comment] 2024-07-02 11:22
Not true. You need to filter the specific account to display the balance for that account, otherwise it will display the total balance of all accounts.

**Closed by jameskokoska** 2024-07-02 11:21 UTC
Labels: enhancement

**Comment by SilentVoid13** [comment] 2024-07-03 16:05
Hi there, selecting "Date Banner Total" does work for *past* transactions but not *future* transactions.

I would love to be able to know my balance based on future payments. 

Example: We are the 03/07 and I have a 1000$ on my account. I know I have a subscription transaction of 100$ on the 15/07. I'd like to be able to see a 900$ above the 15/07 date, although my current balance is at 1000$.

 I believe this doesn't work currently because repetitive or subscriptions transactions "do not count towards your total unless marked paid", which is great. But I also want to be able to know my balance *after* I paid those transactions.

A new option for the "Date Banner Total" setting or a modification of the existing "Net Total" behavior for future transactions would be perfect.

Should I open a new issue or should we re-open this one?

**Comment by jameskokoska** [comment] 2024-07-04 03:42
Edit: 

See FAQ https://cashewapp.web.app/faq.html#future-repetitive-transactions

To be consistent throughout Cashew, transactions that are not marked as 'paid' do not count towards any totals. If you do want them to count towards your future net total in the date banner, mark them as 'paid'. This reason is related and similar to this issue https://github.com/jameskokoska/Cashew/issues/313
