### ISSUE TITLE
[Question] How to show recurring transactions?

### ISSUE THREAD

**Issue by jsrol** [jameskokoska/Cashew#132] opened 2024-01-31 18:42 UTC
**Describe your question**

Hey I am trialing the app on here: https://budget-track.web.app and I cant for the life of me understand how to show all upcoming transactions.  What i mean by that is that my recurring and subscription transactions all only appear once. Even if they are supposed to be multiple times in the same month i only see them a single time.  If i check in transactions or scheduled, i get the same result. Example:

![image](https://github.com/jameskokoska/Cashew/assets/19502683/3c41be4e-c3fd-46bf-b745-62fcc4fc7154)

As you can see, I have multiple transactions setup for every 2 weeks yet they only appear once (you can see there is no further transactions until september). 

So my question is: How do I show all recurring transactions?

**Comment by jameskokoska** [comment] 2024-01-31 21:44
Duplicate of/See https://github.com/jameskokoska/Cashew/issues/88

**Closed by jameskokoska** 2024-01-31 21:44 UTC
Labels: question
