### ISSUE TITLE
[Feature Request] Clearer & More Consistent Hide/Unhide Functionality Throughout the App

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#461] opened 2024-10-07 03:39 UTC
**Is your feature request related to a problem? Please describe.**

Currently, the `Add Transaction` screen displays chips for all user accounts, loans, goals and budgets. This becomes problematic if users have many accounts or actively use loans. The screen, one of the most frequently used, ends up cluttered. In my case, I have to scroll through old loans for quite some time just to access the + button.

To hide unwanted loans, a user might go to the `Loans` page and toggle the eye icon next to each loan. However, while this hides the loans on the `Loans` page, they still appear greyed out on the `Add Transaction` page, introducing a third state that is neither hidden nor unhidden, which is counterintuitive. The same issue occurs with budgets and goals.

There doesn't seem to be any reason why a user would want to see long-settled loans, irrelevant budgets/goals, or accounts from banks that might be closed by now every time they add a new transaction.

**Describe the solution you'd like**

A clearer and more consistent hide/unhide functionality would solve this problem that many users will face as their data grows:

**If a loan is toggled as hidden/unhidden on the Loans screen, it should be hidden/unhidden throughout the app. The same logic should apply to Budgets, Goals, and Accounts.**

This straightforward approach would give users control over old loans, budgets, and accounts when they start getting in their way.

**Comment by jameskokoska** [comment] 2024-10-07 03:44
Duplicate of https://github.com/jameskokoska/Cashew/issues/260 and https://github.com/jameskokoska/Cashew/issues/265

**Closed by jameskokoska** 2024-10-07 03:44 UTC
Labels: enhancement
