### ISSUE TITLE
[Question] How to import Credit Card Statement CSV file which contains subcategory?

### ISSUE THREAD

**Issue by offline136** [jameskokoska/Cashew#202] opened 2024-03-29 03:00 UTC
So, I have created a Category named "Bills" and under Bills, I have 2 subcategories named "Phone Bill" and "Internet Bill".
Now, I want to import a CSV file of my credit card statement which I have edited as required/recognized by Cashew. Cashew format only contains a column of "Category". But, I want to put my Phone bill and Internet bill under their own Subcategory.
(1) If I put "Phone Bill" in the "Category" column then it creates another category of "Phone Bill" once I successfully import data. 
(2) If I create an extra column in the CSV file named "Subcategory" then while importing the data, I have to specify which column's data I have to put under the "Category" of the transaction. This means I have to select data of either "Category" or "Subcategory" Which is not helpful because some of my expenses belong to the Category and some of my expenses belong to the subcategory.
(3) If I put my Subcategories under the Notes column then I can select subcategory data instead of notes while importing the data. But, it will just write my subcategories into the notes section. 

My ask is how am I able to import transactions with Subcategories? If I have to manually change categories then it's better to enter expenses manually altogether. Because, to import data, I have to modify lots of things in CSV files to begin with. Now, changing subcategories of expenses manually will take so much extra time. In the end, I am spending as much time in automating things, as I would spend in manual entries.  Any suggestion? 

Thank you \m/

**Comment by ngocanhtve** [comment] 2024-03-29 03:04
Thats simple. Just import Bills and Phone Bills as a main category into Cashew first. Then go to category settings and make Phone Bills into a subcategory of the Bills category.

**Comment by jameskokoska** [comment] 2024-03-29 03:05
Duplicate of https://github.com/jameskokoska/Cashew/issues/87

**Closed by jameskokoska** 2024-03-29 03:05 UTC
Labels: question

**Comment by jameskokoska** [comment] 2024-03-29 03:09
If you are interested in automating Cashew to the fullest, consider using App Links. Documentation can be found here: https://github.com/jameskokoska/Cashew?tab=readme-ov-file#app-links

I may make it so that if Cashew finds a subcategory named the same as the category name under the import CSV category column of an entry, it will take that instead.

**Comment by offline136** [comment] 2024-03-29 04:20
> It has been changed so that if a subcategory exists, it will be added to the subcategory so your situation (1) will work.
> Added here: [324dbac](https://github.com/jameskokoska/Cashew/commit/324dbac653acde43014c8e39ed6e131f7b1e4ead)

That was fast. Thank you :)

Also, is there any way to reverse import? I imported CSV file with multiple transactions but forgot to add Negative sign in front of expenses so now they all got imported as Income..!! :(

Please and Thank you.

**Comment by jameskokoska** [comment] 2024-03-29 04:41
Unfortunately there is no way to reverse an input.

**Comment by offline136** [comment] 2024-03-29 04:51
Okay then please add functionality to delete multiple entries together. I have to open all entries individually to delete them. 
Thank you!

So far, I love the app and your great work. I'm just finding some user-friendliness/functionality issues as I dive deeper.

**Comment by jameskokoska** [comment] 2024-03-29 04:52
You can long press transactions and select multiple at once.

**Comment by ngocanhtve** [comment] 2024-03-29 04:53
Why do you think so complicatedly? Just reset the app and complete the csv (add a minus sign) then import again, wouldn't it be simpler and faster?

**Comment by offline136** [comment] 2024-03-29 05:13
> You can long press transactions and select multiple at once.

Perfect. Didn't know about this. Thank you..!

**Comment by offline136** [comment] 2024-03-29 05:15
> Why do you think so complicatedly? Just reset the app and complete the CSV (add a minus sign) then import again, wouldn't it be simpler and faster?

But, I have my previous transactions too. If I reset the app, then everything will be erased right? I don't want that hassle so I better delete them by selecting multiple non-wanted entries. But, thank you for the suggestion. :)

**Comment by ngocanhtve** [comment] 2024-03-29 05:20
Depends on you. There is an option is export the current database to csv and do batch edits on the csv then import back.

**Comment by offline136** [comment] 2024-03-29 05:24
> Depends on you. There is an option is export the current database to csv and do batch edits on the csv then import back.

Okay will try that option as well. Thank you.
