### ISSUE TITLE
[Feature Request] option to exclude a selected recurring transaction 

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#503] opened 2024-11-09 16:03 UTC
I wish if there is an option to exclude some recurring transactions from my total, either to exclude the whole transaction with all recurrences or only single one in one cycle

**Comment by jameskokoska** [comment] 2024-11-09 16:23
Duplicate of https://github.com/jameskokoska/Cashew/issues/172 or you can mark as Skipped for reoccurring transactions

**Closed by jameskokoska** 2024-11-09 16:23 UTC
Labels: enhancement

**Comment by hexman1999** [comment] 2024-11-09 17:41
> Duplicate of https://github.com/jameskokoska/Cashew/issues/172 or you can mark as Skipped for reoccurring transactions

But that button is not there for recurring
