### ISSUE TITLE
[Feature Request] Additional data fields

### ISSUE THREAD

**Issue by Drakon1505** [jameskokoska/Cashew#280] opened 2024-05-26 09:28 UTC
When creating a transaction, it would be cool to include an optional field for the brand name and product weight.

**Comment by jameskokoska** [comment] 2024-05-26 11:26
Duplicate of https://github.com/jameskokoska/Cashew/issues/107 and https://github.com/jameskokoska/Cashew/issues/130

**Closed by jameskokoska** 2024-05-26 11:26 UTC
Labels: enhancement
