### ISSUE TITLE
[Feature Request] Request to reflect balance with green color for positive and red for Negative  in "All spending - > History" screen

### ISSUE THREAD

**Issue by HappyBear-btc** [jameskokoska/Cashew#275] opened 2024-05-21 06:28 UTC
Request to reflect balance (Income - Expense = Balance) in "All spending - > History" screen with corresponding color, green for positive and red for negative.
currently this screen shows income as green and expense as red, but beneath the period where the Income minus Expense is shown the number is not colored.

**Comment by jameskokoska** [comment] 2024-05-21 06:58
Duplicate of https://github.com/jameskokoska/Cashew/issues/219

**Closed by jameskokoska** 2024-05-21 06:58 UTC
Labels: enhancement
