### ISSUE TITLE
[Feature Request] The money transfer option between accounts as a single transaction instead of two transactions.

### ISSUE THREAD

**Issue by codezinfinity** [jameskokoska/Cashew#378] opened 2024-08-18 08:12 UTC
**Is your feature request related to a problem? Please describe.**
When I use the money transfer option between accounts, it shows as two transactions. One is a debit from the 1st account & other is the credit to the second account. But later, when I want to edit the transfer amount, it asks if I want to edit both transactions. I don't know if it's required because if I select NO, only one transaction shows the edited amount and the other one shows the old amount, and the whole point of a TRANSFER option is nullified. because the amounts are not equal. 

**Describe the solution you'd like**
Instead, if you could make the TRANSFER transaction as a single instance, it might be better... just my thought. In case you later edit the transaction and click save. Amounts are updated in both accounts together & no questions are asked about individual values.

**Describe alternatives you've considered**
I have tried out a few other software most of them have it as a single instance.

**Additional context**

Please find attachments.

![Cashew](https://github.com/user-attachments/assets/fd19cec0-4812-4b7a-9a5d-9af7664578fa)

https://github.com/user-attachments/assets/56a38eb2-796d-4658-88e6-98e1ee2bd950

 In the pic, Instead of 2 transactions you could make it as a single one and in the label, you could mention as 
**ENBD DC > DIB DC**

![Cashew1](https://github.com/user-attachments/assets/fe2100df-3916-437d-a517-2767a5dfedc5)

something like this & also at the place of -- you could show the title (ie **Test** in my case) 

And if there is a **NOTE** mentioned in the transaction, at the end, you could show a note symbol as above (may be good if it can be done to all transactions where there is note added so that user can know of it without opening the transaction).

I would love to be part of this development, but unfortunately, no coding knowledge (eventhough my account id is codezinfinity 😎 .. and also, you prefer otherwise). Anyway, will try to provide more feedback. Please do implement, if you feel its Ok. Thx

**Comment by jameskokoska** [comment] 2024-08-18 09:33
Duplicate of https://github.com/jameskokoska/Cashew/issues/93

**Closed by jameskokoska** 2024-08-18 09:33 UTC
Labels: enhancement
