### ISSUE TITLE
[Feature Request] Sub-Accounts / Account Aggregation

### ISSUE THREAD

**Issue by kuhru** [jameskokoska/Cashew#468] opened 2024-10-13 11:10 UTC
Firstly, thanks for making this, it is an amazing app that has ruined my expectations for good UI+UX in apps. This has raised the bar for me, I cannot make do with normal task tracking apps now. Onto the request.

**Is your feature request related to a problem? Please describe.** 🤞

In a bank account, it is possible to have a deposit (like FD) which maybe hardly changes for long periods (mostly static), as well as savings which can go up and down very often (mostly dynamic). To keep track of both, the current solution is to simply make 2 accounts.
However, expand it to 3 Bank accounts, and all having FD, and now I have 6 accounts.
Expand it to having investment, with app ABC. In ABC, the tracking could be "Invested" (in market) or "Uninvested" (in in-app-wallet), so 2 Accounts for every such app if the want is to track money by apps (which is the case, if you want to know "oh this much is with this app").
Expand it to having multiple credit cards. Likely an account for each card.

**Describe the solution you'd like** 🔥

While all these can have their own accounts, sub-accounts where the main account aggregates the subs would be a wonderful solution for all these cases.
On dashboard, the user can choose to pin the sub-accounts like normal ones, or the main account would anyway show the total.
Sub-accounts do everything that accounts do, so transferring and balance correction and everything, just that on dashboard I don't need to see them, I can see an aggregate, and when I go in the aggregate, I can see the combined transaction history of its sub-accounts.

**Describe alternatives you've considered**  😖

Currently what I do:
- For investment case, I do (Uninvested + Invested) as balance correction, because I try to track the current net worth of that account. This would enable me to show transfer from invested to uninvested, and market updates to invested can be balance correction as before. (Btw, love that balance correction by default is not my income or expense, I need that for accurate tracking.)
- For FD case, same, my updates are (FD + Savings) when correcting balance monthly.
- For Credit card case, I have 1 account, and i add the card-name to the notes in every expense/income, so that when I want to check the current history of that card, I can manually search of it.

This does work, its not intuitive, and is human error prone.
Sub-Accounts / Account Aggregation would solve this, and any other similar scenarios wonderfully, while also keeping organized.

**Comment by jameskokoska** [comment] 2024-10-13 14:29
Duplicate of https://github.com/jameskokoska/Cashew/issues/136

**Closed by jameskokoska** 2024-10-13 14:29 UTC
Labels: enhancement
