### ISSUE TITLE
[Feature Request] f-droid

### ISSUE THREAD

**Issue by quentincaffeino** [jameskokoska/Cashew#201] opened 2024-03-28 09:31 UTC
**Is your feature request related to a problem? Please describe.**
f-droid build

**Describe the solution you'd like**
Main benefit is not having tracking/telemetry and not being dependant on google services.

**Describe alternatives you've considered**
Building myself without telemetry.

**Comment by ngocanhtve** [comment] 2024-03-28 10:35
Duplicate of #82, #111.

**Comment by quentincaffeino** [comment] 2024-03-28 11:02
Sorry for not looking enough for duplicates, appreciate the response. I still think the google-less version would be highly appreciated by people who want to have control over their data.

**Closed** 2024-03-28 11:02 UTC
Labels: enhancement

**Comment by ngocanhtve** [comment] 2024-04-01 14:41
>  I still think the google-less version would be highly appreciated by people who want to have control over their data.

Cashew relies on Google Drive for backup and synchronization. As well as premium features, the multiple budgets feature, require Google Play to deploy. There is no way to De-Google 😁
