### ISSUE TITLE
Sliding budget

### ISSUE THREAD

**Issue by AustralEpitech** [jameskokoska/Cashew#555] opened 2024-12-20 03:19 UTC
**Is your feature request related to a problem? Please describe.**
I want to setup a daily budget reported on multiple days. E.g. with a 10 € daily budget: if on the 1st day I use 8 €, then on the 2nd my budget becomes 12 € and if now I use 15 €, then I'll start the 3rd day with only 7 € (10 - 8 + 10 - 12 + 10)

**Describe alternatives you've considered**
Manual calculation

**Comment by jameskokoska** [comment] 2024-12-20 03:42
Duplicate of https://github.com/jameskokoska/Cashew/issues/134

**Closed by jameskokoska** 2024-12-20 03:42 UTC
Labels: enhancement
