### ISSUE TITLE
Sub Categories for Account And a Seperate Total balance Tab

### ISSUE THREAD

**Issue by kumaratv** [jameskokoska/Cashew#430] opened 2024-09-20 01:44 UTC
I have a total of 11 accounts on Cashew, In which :--

- 7 of them is for different banks savings account.
- 2 of them is   to manage my credit card.
- 1 is for cash in physical wallet.
- 1 is for Amazon gift card balance.

 **_Instead of creating 11 different accounts on Cashew we can create only 4 account in which :--_**

1. • One (1) account on Cashew is for all my bank accounts of different financial bank. We may create a main account names **BANK BALANCE** on Cashew, afterwards a different _sub categories_ for _different physical financial banks_ using their name or bank account number under the **BANK BALANCE** account on Cashew.

2. Like bank account One account on Cashew is for managing all my Credit card from different financial institutions using sub categories.

3. One is for cash in my physical wallet.

4. One is for gift card balance is just for record purposes.

A Seperate tab names  **TOTAL** that gives the total money we have, A option should be added like "show in total" during creating a new account on Cashew along with selecting currency and initial balance.

Thank you 🙏
A Cashew's Passionate User.

**Comment by jameskokoska** [comment] 2024-09-20 02:43
Duplicate of https://github.com/jameskokoska/Cashew/issues/136

**Closed by jameskokoska** 2024-09-20 02:43 UTC
Labels: enhancement
