### ISSUE TITLE
[Feature Request] GoCardless sync

### ISSUE THREAD

**Issue by IMNOTIKE** [jameskokoska/Cashew#499] opened 2024-11-07 19:37 UTC
Creating the expense/income records manually can be frustrating and one can forget about it and lose track

Apps like Actual Budget make use of GoCardLess for EU banks and other similar services for american banks. Would it be in line with the project to implement some sort of recurring sync with these services?

**Comment by jameskokoska** [comment] 2024-11-07 19:37
Duplicate of https://github.com/jameskokoska/Cashew/issues/33

**Closed** 2024-11-07 19:37 UTC
Labels: enhancement

**Comment by IMNOTIKE** [comment] 2024-11-07 19:40
My bad, hadn't searched old issues thoroughly
