### ISSUE TITLE
[Question] Multiple assets in the same account

### ISSUE THREAD

**Issue by giovaborgogno** [jameskokoska/Cashew#412] opened 2024-09-09 20:17 UTC
**Describe your question**
Is there a way to manage multiple assets in the same account? for example I want to create an account "Metamask" and manage transactions for different cryptocurrencies; or a "Bank" account and be able to add transactions in USD and EUR.
If it is not possible, do you have plans to add this functionality?

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-09-09 20:37
Duplicate of https://github.com/jameskokoska/Cashew/issues/109

**Closed by jameskokoska** 2024-09-09 20:37 UTC
Labels: question

**Comment by giovaborgogno** [comment] 2024-09-09 20:50
Please consider this as a feature that could be added in the future.
thanks, the project is amazing!
