### ISSUE TITLE
Improve ‘collect’ functionality for short-term loans

### ISSUE THREAD

**Issue by kevinah95** [jameskokoska/Cashew#564] opened 2024-12-27 06:31 UTC
**Is your feature request related to a problem? Please describe.**
I’m frustrated because when I select the “collect” option for a short-term loan, the transaction of the collected money does not appear in the transaction history. Additionally, the money is deposited into a different account than the one I originally used to transfer the funds to the other person.

**Describe the solution you'd like**
I would like the following improvements to the “collect” functionality:
	1.	When the “collect” button is pressed, the transaction should appear in the transaction history for better tracking and clarity.
	2.	Allow users to select the account where the collected money should be deposited, providing more flexibility and control over the process.

**Describe alternatives you've considered**
An alternative could be to have a default account preselected for deposits, but allow users to change it before confirming the collection. This would simplify the process while maintaining flexibility.

**Additional context**
This feature would enhance user experience and make the loan collection process more transparent and adaptable.

**Comment by jameskokoska** [comment] 2024-12-27 06:40
you can “partially collect” a one time loan. This is a duplicate of #350 and #106

**Closed by jameskokoska** 2024-12-27 06:40 UTC
Labels: enhancement
