### ISSUE TITLE
Bill splitter UI tweaks suggestion

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#122] opened 2024-01-16 07:35 UTC
**Is your feature request related to a problem? Please describe.**
1.Bill splitter is a very useful tool which is kept way deep in the settings which is frustrating to go into settings each time to split a bill with other persons.

2.Need more ways of splitting bills .

3.when I partialy collect my loans (or in this case bill splitted with my friends) from each person I can't note who have to still pay and who already made the payment.

**Describe the solution you'd like**
1.It can be brought to "Add transaction" page directly where it can be used while adding a transaction and not going through "more tab>settings>split bill"

2.splitting bills by entering the amount each person have borrowed/have to pay

3.Need another partially collecting option of loans in persons wise with whom I splitted the bill in the 1st place. this can be brought in this loans page where people with the amount to be paid can bee seen with a check box.
![Screenshot_20240116_130108.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/0a0fb3a9-a2c5-4715-85a1-cfc15d89c969)
By checking the box I can create a collected transaction (that too can be fully collected or partialy collected🙃 if possible).
Like I can have names of persons with whom I split the bill and mark the payment from this page which adds as transaction 

**Additional context**
This is the way google pay can split bills and I too prefer it.

https://github.com/jameskokoska/Cashew/assets/121549490/bb3faced-14ba-47c8-ac7c-fd76d2f50b95

https://github.com/jameskokoska/Cashew/assets/121549490/b1a94c20-421a-4ace-aa3e-a49169d4c555

🙃I already tried explaining this in #68 but got closed . But I hope you read this and trying to add this feature irrespective of it making into the already feature rich awesome app❤️

**Comment by jameskokoska** [comment] 2024-01-16 12:52
Hi there! I appreciate the clarification, however please continue discussions on your previously related tickets. Do not open duplicates, especially ones that you have already created and acknowledged.

The way Google Pay splits bills is different than that of Cashew. If you prefer this method, then you are free to use that tool instead, especially since it suits your needs better. Cashews bill splitter is more precise in itemized splitting and was designed in such a way. Bill splitting is not the focus of this app. There are full apps meant for this; for example SplitWise.

Cashew generates loan transactions per person, so when they are marked as collected; that persona amount is shown as collected. You can also add notes to transactions after collecting money to add in the person you collected from. The app does not prevent you from adding notes to loan transactions 

Please see this issue for more insights:
https://github.com/jameskokoska/Cashew/issues/86#issuecomment-1859256710

**Closed by jameskokoska** 2024-01-16 12:52 UTC
Labels: enhancement
