### ISSUE TITLE
Accounts Future balance feature

### ISSUE THREAD

**Issue by Ahmed-Abosamaha** [jameskokoska/Cashew#389] opened 2024-08-23 15:40 UTC
based on the recorded recurring/scheduled transactions I propose to add a new recorder on the homepage in order to display the future balance of each account for a specific period.

**Comment by Ahmed-Abosamaha** [comment] 2024-08-23 15:41
Accounts Future balance feature

**Comment by jameskokoska** [comment] 2024-08-23 15:42
Duplicate of https://github.com/jameskokoska/Cashew/issues/315

**Closed by jameskokoska** 2024-08-23 15:42 UTC
Labels: enhancement

**Comment by Ahmed-Abosamaha** [comment] 2024-08-24 03:47
Can you explain as I didn't understand

**Comment by Ahmed-Abosamaha** [comment] 2024-08-24 03:51
I mean based on recorded recurring transaction 

How Can I know the future balance for certain account after 6 month for example

**Comment by jameskokoska** [comment] 2024-08-24 13:36
As mentioned in the reference issue: 

To be consistent throughout Cashew, transactions that are not marked as 'paid' do not count towards any totals. If you do want them to count towards your future net total, mark them as 'paid'. This reason is related and similar to this issue https://github.com/jameskokoska/Cashew/issues/313

Please do not duplicate issues, you can reference the duplicate thread to find your issues already addressed with an answer.
