### ISSUE TITLE
[Feature Request] Custom period on the transactions page

### ISSUE THREAD

**Issue by ghost** [jameskokoska/Cashew#236] opened 2024-04-23 08:59 UTC
Let me start and say THANK YOU for this amazing app. This is one of my favourite apps for budgeting (I'm using three at the moment, but hopefully I would be able to move to just this app). I do apologise if someone already asked for this (I tried to look for something similar in the earlier feature requests), or if this is already possible, and I have just not found the setting.

**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]
As you can put a custom period to the budgets and many other places, it would be amazing if the transactions page would allow custom start date of the month. At the moment, my salary would go to the previous month's view, and for me, it is harder to follow the transactions this way.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It would be good if you can have a specific period, e.g. 28.4-27.5 instead of a static month on the transaction page. This would make it easier to see what spending you have had after getting paid. An app that does this well is MyExpenses.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]
Another option could be to have a period filter in the filters section on the transaction page, but a select period pop-up would be the best.

**Additional context**
[Add any other context or screenshots about the feature request here.]

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

Thank you again for this great app.
Kind regards.

**Comment by jameskokoska** [comment] 2024-09-23 17:22
Duplicate of https://github.com/jameskokoska/Cashew/issues/104 and see https://github.com/jameskokoska/Cashew/issues/433

**Closed by jameskokoska** 2024-09-23 17:22 UTC
Labels: enhancement
