### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by anthony-kyle** [jameskokoska/Cashew#256] opened 2024-05-01 22:25 UTC
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]

With Long Term Loans, especially those such as Home loans or even smaller ones where there is interest charged, there is no way to add the interest fee against the loan without adding a "collected" type transaction which then deposits that amount in an account which then needs to be offset by a balance correction. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

It would be amazing to be able to have the ability to add interest expense to a loan which only applies to it's own balance offsetting any payments made to the loan (or even increasing the loan amount if interest goes above the initial) without it counting as actually recieving any money.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

I identified 3 work arounds in app.
1. Continually add the interest to the offset as this achieves the result, but is cumbersome to manage and has no audit trail
2. Add a specific account for "managing" the loan interest and payments, transferring money to that account and then flagging that payment as a loan payment. This worked, however was very confusing as there were multiple records for a single transaction and I spent way too much time every time calculating the offsets and ensuring I flagged the correct transaction as doing so would invert the deposit transaction and needed balance confirmation.
3. Manage it in primary account and add a balance correction for each interest that occurs. The easiest to manage solution, but double entry of the interest is cumbersome.

**Additional context**
[Add any other context or screenshots about the feature request here.]

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-05-01 22:38
Duplicate of https://github.com/jameskokoska/Cashew/issues/182

**Closed by jameskokoska** 2024-05-01 22:38 UTC
Labels: enhancement
