### ISSUE TITLE
[Feature Request] Adding Credit Card details similar to bank account

### ISSUE THREAD

**Issue by Nithin3008** [jameskokoska/Cashew#451] opened 2024-10-01 14:00 UTC
**Is your feature request related to a problem? Please describe.**
I have multiple credit cards while using them I am unable to track it. Since during the bill payment it was total confused as the numbers never same after payment.

**Describe the solution you'd like**
Allowing users to a credit card similar to bank account with billing dates if possible cards connecting to respective bank account. Option to select credit card while adding the transaction. Option like pay bill will deduct the amount from bank account.

**Comment by jameskokoska** [comment] 2024-10-01 14:04
Duplicate of https://github.com/jameskokoska/Cashew/issues/124

**Closed** 2024-10-01 14:04 UTC
Labels: enhancement
