### ISSUE TITLE
[Feature Request] Split transaction  - negative amount

### ISSUE THREAD

**Issue by mn9891** [jameskokoska/Cashew#240] opened 2024-04-25 02:04 UTC
First, thanks a lot for the great app!

Here's few nice features that would be great for the app to support:

- the ability to split a transaction into multiple categories
For example you have a 100$ transaction on your credit card, 60$ is Grocery and 40$ is for Clothing

- one more useful thing to have is the ability to set the transaction amount to negative values.. sometimes you get a refund, like an insurance or something and it is more precise to have that as -1000 in expense rather than a 1000 in income (otherwise it incorrectly inflates the income)

Thanks!

**Comment by jameskokoska** [comment] 2024-04-25 02:16
Duplicate of https://github.com/jameskokoska/Cashew/issues/216

If you want to issue a refund, you can exclude the amount (https://github.com/jameskokoska/Cashew/issues/203), delete the transaction, or add an equivalent income amount

**Closed by jameskokoska** 2024-04-25 02:16 UTC
Labels: enhancement

**Comment by pengweizhong** [comment] 2024-04-30 01:46
useful

**Comment by pengweizhong** [comment] 2024-05-11 09:07
> Duplicate of #216 and #65
> 
> If you want to issue a refund, you can exclude the amount (#172), delete the transaction, or add an equivalent income amount

I just discovered a new logic problem, I just spent 50 on the platform when I bought groceries, and afterwards the platform refunded me 1.29 due to insufficient weight, so my actual expenditure should be (50-1.29=48.71).  Therefore, in the excluded amount, please add the function of customizing the excluded amount, thank you.

**Comment by anjuthanmj** [comment] 2024-05-22 05:21
@jameskokoska I was searching for this feature and found this thread. The solution you have mentioned only works for full refund. I add discounts or rebates this will be difficult. These days it is very common to get discounts on total bills. Let's say I buy four groceries items and receive 10% on the total bill. I will require to manually deduct 10% from all four transaction entry or deduct the total discount from one transaction. If I do the later, the price of that item is not accurate. By enabling to enter a transaction with negative value with a title 'discount', the total amount paid will be reflected in account balance. 

Adding it as income is not accurate again as if my salary is say 1000 bucks for the month, I make more sense to keep it as 1000 instead of adding discount and rebates to income and make it look like 1025 etc. 

The solution by @pengweizhong to alter excluded amount also will work. 

The previous app I used allowed me to do this which was convenient. Hope you will consider it.

**Comment by DataEnginr** [comment] 2024-09-14 12:06
Even I am looking for the solution to this problem.. @jameskokoska please add a feature to add partial refunds
