### ISSUE TITLE
[Question] Self hosted option?

### ISSUE THREAD

**Issue by surya9teja** [jameskokoska/Cashew#340] opened 2024-07-25 15:22 UTC
**Describe your question**
Do you plan to implement self hosted option?

Great project and really nice UI but it would be great if we can self host this project in home lab or somewhere. Any plans for that in future?

**Comment by jameskokoska** [comment] 2024-07-25 17:03
Cashew does not have a backend that needs hosting. 

This is a duplicate of https://github.com/jameskokoska/Cashew/issues/296 and https://github.com/jameskokoska/Cashew/issues/84

**Closed by jameskokoska** 2024-07-25 17:04 UTC
Labels: question

**Comment by Nirzak** [comment] 2025-03-31 18:04
> Cashew does not have a backend that needs hosting.
> 
> This is a duplicate of [#296](https://github.com/jameskokoska/Cashew/issues/296) and [#84](https://github.com/jameskokoska/Cashew/issues/84)

I think he tried to mean whether we can deploy the web app to our server instead of firebase or not? Is there any way we can do it? Thanks
