### ISSUE TITLE
[Feature Request] option to add sub transactions within a transaction.

### ISSUE THREAD

**Issue by rusted-dreams** [jameskokoska/Cashew#460] opened 2024-10-06 11:09 UTC
**Is your feature request related to a problem? Please describe.**
There are times when we need to add multiple transaction within one. For example, Suppose i went on a trip and spent some amount on food, some in travel, some in shopping.... in that case it would be great if we can club all those expenses under one vacation/trip transaction. and also we can also track the individual categories (i.e. how much we spend on food, travel, shopping, hotels/stays....)

**Describe the solution you'd like**
when we add a new transaction, it would be great if we get an option to add sub expenses like 500 in food category, 1000 in travel, 4000 in shopping, 2000 in hotels/stays. the parent transaction will be the total of all those expenses and this will be the expense that will be shown in the transactions/expenses tabs. But there will also be category wise update like 500 will be added to the food, 1000 to the travel.... This will help in more accurate tracking of each category.

**Comment by Anu6is** [comment] 2024-10-06 13:13
One possible approach could be to use a budget for the trip. By associating all your trip-related expenses with a specific budget, you’d not only be able to track each category individually but also keep an accurate record of each expense's date.

If you had a single transaction with sub-transactions, it would only reflect one date, which may not work well if your trip spans multiple days. Using a budget allows for tracking each transaction independently, ensuring accurate date and category tracking while still allowing you to view the total expenses under one umbrella.

**Comment by jameskokoska** [comment] 2024-10-06 13:36
@Anu6is Thanks for chiming in! Yes the best solution would to create an "Added only" budget type. The example provided in the application is very similar to the use case you propose (Vacation budget)

![image](https://github.com/user-attachments/assets/ea0ebd1b-25cf-4f28-8684-4a32b89d1732)

This is also an indirect duplicate of https://github.com/jameskokoska/Cashew/issues/65

**Closed** 2024-10-06 13:36 UTC
Labels: enhancement

**Comment by rusted-dreams** [comment] 2024-10-06 19:32
yup this solves the trip related issues but lets take another senario. If I went shopping and I bought something for food, grocery, clothing, books, electronics. Do I need to individually put all the expenses in each category or there's also some other way to put them under one umbrella??

**Comment by Anu6is** [comment] 2024-10-06 19:59
Yes, you'd officially put these under their own category. Not sure why you'd want to group them exactly. At most, the calendar view would list only the transactions that occurred on that day.
