### ISSUE TITLE
[Feature Request] Nextcloud integration

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#504] opened 2024-11-09 16:06 UTC
I wish i can use my home server to backup instead of google, in some automated way instead of backing up then uploading to Nextcloud

**Comment by jameskokoska** [comment] 2024-11-09 16:21
Duplicate of https://github.com/jameskokoska/Cashew/issues/84

**Closed by jameskokoska** 2024-11-09 16:21 UTC
Labels: enhancement
