### ISSUE TITLE
[Feature Request] Automatic backup for local backup

### ISSUE THREAD

**Issue by l2eused** [jameskokoska/Cashew#428] opened 2024-09-18 02:15 UTC
## **Describe the solution you'd like**
Add automatic backup for local backup

## **Additional context**
I didn't prefer to use drive (cloud) storage to backup finance statement (I know it safe, but I still not trust them).

So I hope you can add option to auto backup in several time (with max backup file, for example max 10 backup will create up to 10 files and delete the latest file when it exceed maximum) this can help user to backup via local storage and no need to manual trigger everytime that's might forgot to press backup.

```
NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!
```

**Comment by jameskokoska** [comment] 2024-09-18 03:08
Duplicate of https://github.com/jameskokoska/Cashew/issues/20

**Closed by jameskokoska** 2024-09-18 03:08 UTC
Labels: enhancement
