### ISSUE TITLE
[Feature Request] Specific account features for credit cards

### ISSUE THREAD

**Issue by mizzyc** [jameskokoska/Cashew#320] opened 2024-07-05 12:06 UTC
**Is your feature request related to a problem? Please describe.**
It'd be nice to have specific account features for credit cards, since now it's really hard to manage credit cards expenses and payments.

**Describe the solution you'd like**
1. Specific type of account for credit cards, allowing a different behaviour for the expenses and payments;
2. A way to set the limit of the credit card account, based on my credit card limit;
3. A way to set the billing date of my credit card, automatically sending new expenses to the next month when the bill is already closed;
4. A way to transfer the negative balance from my credit card account to my bank account, when I make the payment of the bill;
5. When making the payment of the credit card bill, transfer all the expenses to my bank account, allowing to keep the categories and having track of where my money is going, besides of just registering as "paid the credit card bill".

**Additional context**
I don't know if there's already a way to do it, since I've just started using Cashew. So I'm sorry if I just don't know how to use it correctly 😅
I've seen there's some FR about this here, but I have some new suggestions and also grouped them all in just one.

**Comment by jameskokoska** [comment] 2024-07-05 13:44
Duplicate of https://github.com/jameskokoska/Cashew/issues/124

**Closed by jameskokoska** 2024-07-05 13:44 UTC
Labels: enhancement
