### ISSUE TITLE
[Feature Request] Support adding a transaction amount with different currencies

### ISSUE THREAD

**Issue by Esildor** [jameskokoska/Cashew#527] opened 2024-11-22 22:06 UTC
**Is your feature request related to a problem? Please describe.**
When traveling and making purchases in different countries, I log all my transactions. With every transaction, I have to convert the price to my account's preferred currency before submitting. 
Example:
- All my accounts are set to use USD, my preferred currency.
- I buy a cup of coffee for 2 Euro
- I don't know the conversion rate of 2 Euro to USD when logging the transaction (in USD)
- I must manually search & convert the amount
  - I google it and get the result
- I enter 2.08 as the transaction amount, since it is the amount I've actually spent

**Describe the solution you'd like**
A button on the _Add Amount_ UI is used to convert to any of the selected and supported currencies. Ideally, the selected currency persists until I change it to something else. Perhaps something similar to this UI:
![image](https://github.com/user-attachments/assets/b140e75c-dfab-4afe-a00d-88a0433482b9)

**Describe alternatives you've considered**
I've checked this [section in the FAQ](https://cashewapp.web.app/faq.html#multiple-currencies), but don't think it's relevant here to this use case, unless I'm missing something. That link describes managing **accounts** with different currencies, not transactions. Ultimately, as a user, I'm fine with the rule of:
> Cashew only supports one currency per account.

However, I would like it to do some conversion for me. Which the app supports elsewhere.

**Additional context**
This seems like an extremely popular use case, so much so, I'm worried I'm missing if this feature already exists and I don't know about it. Many people go on vacation for weeks at a time in different countries. They want to log all their transaction in cashew in the local currency, since that what they see on signs and receipts. Ultimately, only care about currency from my home country (I understand this isn't the case for everyone, but it is the most common). For more context, my accounts in Cashew replicate my real-world accounts:
- Checking
- Savings
- Credit Card
- Cash
I want to see my spending across all these accounts, in my preferred currency, without having to manually convert.

Also, shout out to all the amazing devs of this app, happy to be a pro user! Love it! 💖

**Comment by Esildor** [comment] 2024-11-22 22:28
Also, I can feel the comment coming of:
> Duplicate of #109 

However, this feels really clunky. Make an account, that I never log transactions too, then delete it at the end of the trip? Just display this button on the Add Amount UI. Could even be disabled by default. Then I could only turn it on for trips.

**Comment by jameskokoska** [comment] 2024-11-22 23:00
Duplicate of https://github.com/jameskokoska/Cashew/issues/109

**Closed by jameskokoska** 2024-11-22 23:00 UTC
Labels: enhancement

**Comment by jameskokoska** [comment] 2024-11-22 23:03
The currency conversion button requires another account to be selected so that Cashew knows what your currency of purchase was. You can convert it into your primary currency using the in place conversion button you attached a screenshot of. 

Apart from creating a temporary account, what are the issues with the current implementation? The temporary account is used because Cashew will know what your source currency is.

**Comment by jameskokoska** [comment] 2024-11-22 23:04
> Wow, can I get a refund?

Sorry I’m trying to work with you on this - I would appreciate some patience. If you would like a refund, please reach out on email and I can provide you one.
