### ISSUE TITLE
[Feature Request] Be able to choose the backup folder

### ISSUE THREAD

**Issue by acress1** [jameskokoska/Cashew#484] opened 2024-10-26 12:19 UTC
Hello,

At the moment, when we backup locally, the file is saved in the Download folder, with a specific name.
It would be awesome to have a feature to choose the folder (for example I would like to save all the backups in a new folder "Cashew Backups"), and also that the app automatically creates a new backup file as soon as something is modified.
The syncing would be managed afterwards with SyncThing and not with GDrive.

Thanks !
Best regards
cress

**Comment by jameskokoska** [comment] 2024-10-26 13:24
Duplicate of https://github.com/jameskokoska/Cashew/issues/20

**Closed by jameskokoska** 2024-10-26 13:24 UTC
Labels: enhancement
