### ISSUE TITLE
Editable transfer rate upen entering transactions between different currency accounts

### ISSUE THREAD

**Issue by NS-H** [jameskokoska/Cashew#269] opened 2024-05-16 23:07 UTC
Requesting a feature enhancement to allow manual editing of the transfer rate and transaction fee when recording transactions between different currency accounts. This is crucial for handling volatile currencies like Bitcoin (BTC).

1. Manual Rate Entry: Enable input of the exchange rate during transaction recording or allow entering amounts spent and received, with the system calculating the rate.
2. Transaction Fee Entry: Add a field to input the transaction fee.

These changes will ensure accurate tracking of currency transactions, reflecting real-world exchange rates and fees.

**Comment by jameskokoska** [comment] 2024-05-16 23:10
Duplicate of https://github.com/jameskokoska/Cashew/issues/230

**Closed by jameskokoska** 2024-05-16 23:10 UTC
Labels: enhancement
