### ISSUE TITLE
[Feature Request] Add transaction to multiple budgets

### ISSUE THREAD

**Issue by lpranam** [jameskokoska/Cashew#483] opened 2024-10-26 04:03 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if i can add transactions to multiple budgets. Or merge multiple budgets with some kind of tags which can indicate original transaction budget etc...

**Comment by jameskokoska** [comment] 2024-10-26 04:04
Duplicate of https://github.com/jameskokoska/Cashew/issues/353

**Closed by jameskokoska** 2024-10-26 04:04 UTC
Labels: enhancement
