### ISSUE TITLE
[Feature Request] Ability to archive an account

### ISSUE THREAD

**Issue by webpixeldesign** [jameskokoska/Cashew#514] opened 2024-11-15 04:02 UTC
**Is your feature request related to a problem? Please describe.**
I know we can hide accounts from account list widget on homescreen, but these account still show up in the transaction adding screen. I have closed 2 bank accounts and 2 credit cards since i started using this app. And I can't hide these account from the list without deleting them. It takes more scrolling to reach other accounts.

**Describe the solution you'd like**
Ability to archive accounts like we can do goals, etc. Hides the account from everywhere other than the accounts screen in settings. Doesn't hide transactions.

**Describe alternatives you've considered**
None tbh. One of the account I closed was Jio Payments Bank Account, as I only used it for a month, I manually transferred all the transactions to my other account.

**Additional context**

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-11-15 04:14
Duplicate of https://github.com/jameskokoska/Cashew/issues/265

**Closed by jameskokoska** 2024-11-15 04:14 UTC
Labels: enhancement
