### ISSUE TITLE
[Feature Request] Exclude & Include sub categories from Budget

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#334] opened 2024-07-17 10:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently while configuring budget, we get an option to include & exclude categories. 
**Describe the solution you'd like**
The exclusion/inclusion should be configurable at subcategory level. 

**Describe alternatives you've considered**
Currently need to create different categories to include/exclude in the budget. But logically they can be bundled in same category hence it creates a conflict. 

**Additional context**
[Add any other context or screenshots about the feature request here.]

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment] 2024-07-17 11:24
Duplicate if #110

**Comment by jameskokoska** [comment] 2024-07-17 11:24
Duplicate of #110

**Closed** 2024-07-17 11:24 UTC
Labels: enhancement
