### ISSUE TITLE
[Feature Request] Account Grouping

### ISSUE THREAD

**Issue by shackra** [jameskokoska/Cashew#330] opened 2024-07-15 10:12 UTC
**Is your feature request related to a problem? Please describe.**
I have savings on THORSWAP, and each savings in there is associated to a crypto-wallet, from 2 or 3 different cryptocurrencies. I'd like to re-use account names without confusing each account when inserting a transaction or doing a transfer.

**Describe the solution you'd like**
Logical Grouping of accounts up to 3 level. Thus we can represent things like this:

- THORSWAP
  - Bitcoin
    - emergency funds (index 1)
    - PC parts (index 0)
- Ledger Nano X
  - Bitcoin
    - savings (index 1)
    - personal (index 0)

Maybe grouping by cryptocurrency is overkill on this case, but for platforms like Binance where they can have more than one place to keep your assets may come handy (i.e.: funds wallet, spot walle, Simple Earn, etc)

**Describe alternatives you've considered**
Having a large account name and separating the bits of information with dashes lol

**Additional context**
[Add any other context or screenshots about the feature request here.]

(I've searched the issue tracker for something similar to this and found nothing!)

P.s.: this app is way better and convenient than Wallet by Budgetbakers and other alternatives out there!

**Comment by jameskokoska** [comment] 2024-07-15 13:24
Duplicate of https://github.com/jameskokoska/Cashew/issues/136

**Closed by jameskokoska** 2024-07-15 13:24 UTC
Labels: enhancement
