### ISSUE TITLE
Sub bank accounts inside bank account

### ISSUE THREAD

**Issue by Zidrenn** [jameskokoska/Cashew#399] opened 2024-08-26 16:03 UTC
Hi, first I need to say that this app is amazing. The best I've tried and that's why I probably won't change it for any reason.
Now, my "problem"... Im here to ask for a resource that can organize my bank accounts information.
I have a Revolut account where I have my money, but I have money in various different currency. Right now, to have all this information separated in the app, I need to create multiple accounts for each currency.

I'm here to suggest having bank subaccounts (more or less like subcategories), where I can have, within one bank account, several accounts with different currencies. However, all the money belongs to the same account.

Thank you very much.

**Comment by jameskokoska** [comment] 2024-08-26 16:12
Duplicate of https://github.com/jameskokoska/Cashew/issues/136

**Closed by jameskokoska** 2024-08-26 16:12 UTC
Labels: enhancement
