### ISSUE TITLE
[Feature Request] Daily Budget Widget

### ISSUE THREAD

**Issue by 32mgKoffein** [jameskokoska/Cashew#554] opened 2024-12-18 07:56 UTC
I really love the calculated budget per day, which you see in when you look at a budget in the app.

I think if I would have this information as a widget on the home screen, it would help me to have a really good overview on how I should structure my expenses for the rest of the day.

**Comment by jameskokoska** [comment] 2024-12-18 14:51
Exact duplicate of https://github.com/jameskokoska/Cashew/issues/125

**Closed by jameskokoska** 2024-12-18 14:51 UTC
Labels: enhancement
