### ISSUE TITLE
[Feature Request] Add the description field to the accounts & budgets.

### ISSUE THREAD

**Issue by sohilsshah** [jameskokoska/Cashew#479] opened 2024-10-22 20:35 UTC
Can you add the description fields to the accounts & budgets?

I want to add description about account so I can save the basic account info or notes in that description field.

Same goes for the Budgets. I need to add notes to budgets. So I don't have to recall or check it from info stored somewhere else!

It will be more useful and easy to use app. And it may be my one stop solution!

**Comment by jameskokoska** [comment] 2024-10-22 20:42
Duplicate of https://github.com/jameskokoska/Cashew/issues/319

**Closed by jameskokoska** 2024-10-22 20:42 UTC
Labels: enhancement

**Comment by sohilsshah** [comment] 2024-10-23 08:49
Notes like private information isn't the only case. I just want to write the purpose of account and budget which can't be understood by name only. And adding purpose inside the name will be too long too.

It can have a placeholder like, "Cashew is not encrypted and data exports are not encrypted. We don't encourage users to store personal information within Cashew."
